### ISSUE TITLE
Modify "GLFW Window" in glfw2 source code to be blank

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#679] opened 2017-04-12 21:34 UTC
When a Defold project opens its window title begins as "GLFW Window" before the game is loaded. This would be better to be a blank instead instead of what GLFW uses as a default.

![2017-04-12 14_28_00-glfw window](https://cloud.githubusercontent.com/assets/409170/24980248/529c126a-1f8c-11e7-8680-c8d844a70d68.png)

Alternatively during the bundle process the exe could be hex patched to change the default title to the project title so it looks better when running... that is the work around I'm doing for now.

**Comment by britzl** [comment] 2018-08-28 09:50
Duplicate of https://github.com/defold/editor2-issues/issues/1281

**Closed by britzl** 2018-08-28 09:50 UTC
Labels: engine
