### ISSUE TITLE
Bug with scrollbar in code editor

### ISSUE THREAD

**Issue by wyrmling** [defold/editor2-issues#1022] opened 2017-06-24 15:23 UTC
Seems that scrollbar is "jumping" (showing and hiding) when long line following very soon after the screen.
Please look at attached gif.

![scrollbar_bug](https://user-images.githubusercontent.com/13387159/27509606-94d3f308-5909-11e7-8f2b-a7e4a36b3fe0.gif)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.107</td></tr>
<tr><td>Defold sha</td><td>86632bf7cdeb8d9833baff3864fe480c1162f8da</td></tr>
<tr><td>Build time</td><td>2017-06-22T10:48:42.692440</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment] 2017-06-26 09:31
Duplicate of #890

**Comment by erikangelin-king** [comment] 2018-01-08 16:17
Fixed in new code editor

**Closed by erikangelin-king** 2018-01-08 16:17 UTC
Labels: duplicate, text-editor
