### ISSUE TITLE
Editor stalls every second for half a second

### ISSUE THREAD

**Issue by gregor-king-gullwi** [defold/editor2-issues#144] opened 2016-11-08 07:19 UTC
If I open our project in the editor on OS X and open a collection and move the mouse around, the CPU spikes every second and freezes the editor for half a second (noticeable on the mouse position markers on the rulers on the sides), making it pretty much unusable.

![skarmavbild 2016-11-08 kl 08 12 14](https://cloud.githubusercontent.com/assets/21033075/20090081/3b566478-a58b-11e6-9310-12038fcbd428.png)

**Comment by ragnard-king** [comment] 2017-01-30 13:36
@gregor-king-gullwi Hi Gregor! Have you tested editor2 again recently? Would be interested to hear if you still experience this issue.

**Comment by gregor-king-gullwi** [comment] 2017-01-31 05:15
I'm currently on parental leave, so I can't check this for a few months on the same computer setup.

**Comment by RagnarSvenssonKing** [comment] 2017-07-13 08:13
Closing this as unable to reproduce. Please open a new issue if you see the problem again.

**Closed by RagnarSvenssonKing** 2017-07-13 08:13 UTC
Labels: more-info, serious
