### ISSUE TITLE
Something related to bootstrap. 

### ISSUE THREAD

**Issue by tigerteeth** [defold/editor2-issues#1816] opened 2018-04-15 19:34 UTC
### Expected behaviour
build the game after changing bootstrap. I am using Britzl's special build. 
### Actual behaviour
get error message.
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-03-12T11:14:21.310739</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>f492e7b20f5ec0f791bfb9ee501e09c5f6745c92</td></tr>
<tr><td>Defold engine sha</td><td>f492e7b20f5ec0f791bfb9ee501e09c5f6745c92</td></tr>
<tr><td>Defold version</td><td>1.2.123</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"ec88795dd4bf4feabbf1c33fbc63debf"'>ec88795dd4bf4feabbf1c33fbc63debf</a></td></tr>
<tr><td>GPU</td><td>Intel HD Graphics 5000 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.10.18</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.1</td></tr>
<table>

**Comment by erikangelin-king** [comment] 2018-04-16 07:39
Closing this as duplicate of #1783

**Closed by erikangelin-king** 2018-04-16 07:39 UTC
Labels: duplicate, serious
