### ISSUE TITLE
Double click material tag "java.lang.ClassCastException: javafx.scene.Scene cannot be cast to javafx.scene.control.ListView"

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#935] opened 2017-05-25 21:07 UTC
![2017-05-25 14_06_20-defold editor 2 0 - subsoapmisc](https://cloud.githubusercontent.com/assets/409170/26470698/7956240c-4153-11e7-93d0-4516865c4184.png)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.105</td></tr>
<tr><td>Defold sha</td><td>064a1afef152a7a73cc5328eef663dc46a7743f9</td></tr>
<tr><td>Build time</td><td>2017-05-24T13:45:16.973865</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=2ff9ccd6840b44f19c68250b5e0d3057'>2ff9ccd6840b44f19c68250b5e0d3057</a></td></tr>
<table>

**Comment by subsoap** [comment] 2017-05-25 22:21
I have yet to reproduce it.

**Comment by erikangelin-king** [comment] 2017-05-26 07:23
Let me know if you can repro it! Do you remember if you got some other error before this happened? It could be that the application was already in a broken state...

**Comment by subsoap** [comment] 2017-05-26 10:38
Unfortunately I cannot remember in this case. Next time things break somewhere I'll test double clicking a material tag.

**Comment by erikangelin-king** [comment] 2017-05-30 14:00
Hi again! I've really tried to repro this but without success, so closing for now. As usual, please reopen if it happens again!

**Closed by erikangelin-king** 2017-05-30 14:00 UTC
Labels: more-info

**Comment by rgrams** [comment] 2017-09-16 13:03
The same error happened to me today, but I can't reproduce it either. No errors happened before that one, but once it happened the first time it happened again whenever I tried to edit, add, or remove things from the "tags" field on any material. The constants and samplers fields were fine. I restarted the editor and the error stopped, everything works fine. 

<table>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>Defold version</td><td>1.2.113</td></tr>
<tr><td>Build time</td><td>2017-09-13T14:46:12.984175</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4000</td></tr>
<tr><td>Defold sha</td><td>2792f64cbb7bf6209b04b3b8e108167c67b115c8</td></tr>
<tr><td>GPU Driver</td><td>4.0.0 - Build 9.18.10.3165</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=5c02e5461fcd409a9ab4e9a2a763e889'>5c02e5461fcd409a9ab4e9a2a763e889</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>
