### ISSUE TITLE
java.lang.UnsupportedOperationException: Flush is forbidden from target!

### ISSUE THREAD

**Issue by kgoyon** [defold/editor2-issues#2584] opened 2019-05-04 09:17 UTC
### Steps to reproduce
I was importing a library .lua by drag and drop from Finder

<hr/>

<table>
<tr><td>Build time</td><td>2019-04-30T13:23:48.989857</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b8b891be5ba3e650202848d8b84ddc2ca2ed513a</td></tr>
<tr><td>Defold engine sha</td><td>11b1e7662dd68172fca551c52cba248eea16a364</td></tr>
<tr><td>Defold version</td><td>1.2.152</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"3c29c46315cf465c8fc7a4ba049deb5f"'>3c29c46315cf465c8fc7a4ba049deb5f</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Plus Graphics 640</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.4.7</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.3</td></tr>
<table>

**Comment by matgis-king** [comment] 2019-05-06 07:50
Duplicate of #2315 with no additional info. Closing.

**Closed by matgis-king** 2019-05-06 07:50 UTC
Labels: duplicate, jdk, serious
