### ISSUE TITLE
Can't open project from dashboard

### ISSUE THREAD

**Issue by soztrk** [defold/editor2-issues#1099] opened 2017-08-06 13:41 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.110</td></tr>
<tr><td>Defold sha</td><td>f99ec13bc35396b0c5e77a2888962a8702e2fc55</td></tr>
<tr><td>Build time</td><td>2017-08-03T10:29:40.214729</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=bcffc285dfd5459db6e2ebd57db1d84c'>bcffc285dfd5459db6e2ebd57db1d84c</a></td></tr>
<table>

**Comment by erikangelin-king** [comment] 2017-08-06 20:56
Seems to be caused by unicode case folding: https://www.w3.org/International/wiki/Case_folding#Turkish_i.2FI_etc.

**Comment by ragnard-king** [comment] 2017-08-07 11:22
AKA ["The Infamous Turkish Locale bug"](http://mattryall.net/blog/2009/02/the-infamous-turkish-locale-bug)

Working on fix.

**Comment by ragnard-king** [comment] 2017-08-11 09:23
This issue should be resolved in latest update.

**Closed by ragnard-king** 2017-08-11 09:23 UTC
Labels: blocker
