### ISSUE TITLE
fun visual issues with grid view

### ISSUE THREAD

**Issue by needsnaming** [defold/editor2-issues#1043] opened 2017-07-01 03:22 UTC
### Expected behaviour
the viewport should always show the grid in a uniform manner.
The images in the view port should always be rendered accurately

### Actual behaviour
images:
http://imgur.com/a/7zM12
http://imgur.com/a/ctJb9
http://imgur.com/a/74Iz7

when zooming in and out the grid will create the plaid interferance pattern with the grid
also images seem to get random rectangles of a periwinkle color that change with panning and zooming

### Steps to reproduce
It always does this for me. 

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>411f4cf5926fbe89c0893efc16acf48b982d1ae6</td></tr>
<tr><td>Build time</td><td>2017-06-29T17:47:39.795052</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by needsnaming** [comment] 2017-07-01 03:28
Could be machine specific hardware/settings: Here is a dxdiag output.

[DxDiag.txt](https://github.com/defold/editor2-issues/files/1116824/DxDiag.txt)

**Comment by ragnard-king** [comment] 2017-07-03 07:03
@needsnaming Hi! Thanks for reporting this. Judging from the visual artefacts it looks like an instance of this (as of yet unresolved issue): https://forum.defold.com/t/cant-find-the-name-of-intel-icd-opengl-driver/4114. Also, DxDiag says you're using an Intel ICD driver so that matches too. We haven't been able to reproduce this as it seems highly hardware/driver specific but we will try to investigate it further.

**Comment by ragnard-king** [comment] 2017-07-03 07:04
Duplicate of https://github.com/defold/editor2-issues/issues/788

**Comment by needsnaming** [comment] 2017-07-06 06:14
I do not get any errors when using editor 2. I do get errors when using editor 1. 
Disabling my intel onboard graphis card and forcing the editor to use my NVIDIA gpu fixes the issue for me.

**Comment by RagnarSvenssonKing** [comment] 2017-07-06 07:09
I did a quick search on selecting GPU from the app but couldn't find anything useful. All leads points to the user having to specify it when there are multiple GPUs, e.g. in NVIDIA settings specifying the NVIDIA gpu for a particular app. I bet there is some trick to this though, as games typically get the high-performing gpu, but it might also be caused by particular window settings like high-res and fullscreen.
We obviously need to dig deeper into this at some point, but for now the best workaround seems to be to configure it in the drivers for the editor executable.

**Comment by ciw1973** [comment] 2017-07-06 10:40
Yeah, I'm getting something very similar.

[DxDiag.txt](https://github.com/defold/editor2-issues/files/1127558/DxDiag.txt)

**Comment by needsnaming** [comment] 2017-07-06 20:04
@RagnarSvenssonKing 
Can't say if any of these will be of use. But I did a quick search in hopes to help. 
This looks to be helpful. 
https://stackoverflow.com/questions/16823372/forcing-machine-to-use-dedicated-graphics-card
"the process of automatically switching from integrated to dedicated is based on application profiles. Your application is not in the driver's list of known 3D applications"

I suspect this means making an installer will allow you to fix the issue. There is a link on how to inject your driver into the recognized 3d applications list. 

I got there from this article, in case you need other options or that one does not apply. 
https://stackoverflow.com/questions/41779291/force-windows-to-use-the-best-graphic-card-available

@ciw1973 You can manually whitelist the application to use the GPU to fix the graphical issues. 
If you have a NVIDIA GPU, it is under manage 3d settings.

**Comment by ciw1973** [comment] 2017-07-07 09:58
@needsnaming I don't have discrete graphics in the laptop, just an Intel 620 as you'd see from the DxDiag export.

**Comment by RagnarSvenssonKing** [comment] 2017-07-07 10:52
@needsnaming I really appreciate the help, thanks for the links!

**Comment by ciw1973** [comment] 2017-07-07 17:19
Just updated my Intel 620 driver to the latest one available from Dell, and it's made no difference.

See attached images for examples of the type of UI corruption I'm getting.

For what it's worth, it seems to be the same areas of the images which are bad each time, rather than it being random artefacts.

![1](https://user-images.githubusercontent.com/2350088/27968906-c29dabbc-6340-11e7-8ae1-dc6e96e88103.png)
![2](https://user-images.githubusercontent.com/2350088/27968907-c2a316a6-6340-11e7-9def-8525f4873d5a.png)
![3](https://user-images.githubusercontent.com/2350088/27968909-c2abdb56-6340-11e7-83c8-8f8f2e14058f.png)
![4](https://user-images.githubusercontent.com/2350088/27968908-c2aa4a70-6340-11e7-871d-2fb229d5618a.png)
![5](https://user-images.githubusercontent.com/2350088/27968910-c2b1299e-6340-11e7-956e-06bd07631d3f.png)

**Comment by ciw1973** [comment] 2017-07-07 17:25
Worth mentioning that I get the following error eight times in a row when opening an atlas in the original editor (v1.2.107) which is the reason I updated my graphics driver, but it made no difference.

Once the editor is actually open, it'll not show the error again.

![editor v1 opengl error](https://user-images.githubusercontent.com/2350088/27969126-9633a580-6341-11e7-8d22-a8b85cf2d6b8.png)

**Comment by needsnaming** [comment] 2017-07-07 18:46
@ciw1973  I have a few ideas. I will see if I can trouble shoot and find a solution for you over the weekend. 
I'm just a random guy who likes random puzzles. I make no promises. But if I can find a solution it might help them find a solution on their end.

**Comment by ciw1973** [comment] 2017-07-07 18:55
Thanks @needsnaming, really appreciate you looking into this.

Defold appeals to me a lot, mainly because it's 2D I'm interested in, and the remote builds mean I can avoid cluttering my machine with SDKs, but I really don't have much free time at the moment, so for now, I'm probably just going to play with Unity's new 2D tools.

**Comment by needsnaming** [comment] 2017-07-08 07:04
I updated my drivers and still see the same thing. messed with some settings and found nothing that changes things. 

I did some more searching and found an interesting piece of information. My intel driver only officially supports up to openGL 4.4. What version are you using in editor 1 and editor 2? OpenGL's latest version is 4.5 I think.

**Comment by RagnarSvenssonKing** [comment] 2017-07-10 13:14
Thanks a lot for all the help with investigating! I'll spend some more time on this and see what I can find. We should be OpenGL 3 compatible.

**Comment by RagnarSvenssonKing** [comment] 2017-07-11 13:51
Ok, I have now pushed some fixes which should be available in an update in roughly 15 minutes. Since I haven't been able to reproduce the issues, it's mostly guess work and stabs in the dark. What I did:
* Added support for FBOs (if supported by gpu) - some random internet rumors connected similar glitches to Intel HD and pbuffers, which we are using. The FBOs are now preferred over pbuffers, and it seems many drivers have better support for FBOs.
* More specific when requesting the graphics profile. Before we requested the "default" profile. We now specify which GL version needs to be supported. Documentation indicates that it's also more likely to become hardware accelerated this way. I have no idea if this affects which GPU is selected or not.
* Fixed some inconsistencies in how we treat the stencil buffer. Early on, I had a guess that the glitches were a result of stencil testing against a noisy stencil buffer. Now I believe this was *not* the cause of any of the glitches, but the stencil buffer handling is improved anyway.
* GPU data is part of the info when "Report Issue" is used (i.e. the info automatically supplied to the github issues).
* Checks for gl functions that seems to be missing in some drivers, although they belong the API version the driver states to be supporting.

It would be great if you could try the new version and let me know if it fixes anything.

**Comment by ciw1973** [comment] 2017-07-11 15:18
That now seems to work perfectly for me. Many thanks.

**Comment by RagnarSvenssonKing** [comment] 2017-07-11 16:44
Since the fix has been confirmed by @ciw1973, I will close the issue assuming it is indeed fixed. Please submit a new issue in case it happens again (re-submitting will give us more valuable info about your GPUs).

**Closed by RagnarSvenssonKing** 2017-07-11 16:44 UTC
Labels: duplicate

**Comment by needsnaming** [comment] 2017-07-11 20:25
I can also confirm it is fixed for me. Good job!
