### ISSUE TITLE
Make texture field searchable

### ISSUE THREAD

**Issue by blidfors** [defold/editor2-issues#1080] opened 2017-07-25 13:25 UTC
You should be able to search for textures in the texture field of gui nodes.
Minimum expected behaviour would be that of Editor 1 where you could manually enter the path the texture you want.

**Comment by adamwestman** [comment] 2017-07-26 07:43
As an improvement maybe an asset browser, where you could select from available ones and have "recently used" and "recently added".

**Comment by matgis-king** [comment] 2017-07-31 10:03
Duplicate of #849, but you can expect this to be added soon!

**Comment by matgis-king** [comment] 2017-08-01 10:00
You can now type-to-filter inside all Property Editor dropdowns!

**Closed by matgis-king** 2017-08-01 10:00 UTC
Labels: duplicate, feature
