### ISSUE TITLE
I don't know something about fonts

### ISSUE THREAD

**Issue by CocosGames** [defold/editor2-issues#2680] opened 2019-07-09 04:41 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-07-04T15:49:06.027733</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c5bffa56a66c58fa9ef0e3f0a86a8de1f488cad5</td></tr>
<tr><td>Defold engine sha</td><td>d7042d5368c338ed5d66b6dff9c60a20924385ac</td></tr>
<tr><td>Defold version</td><td>1.2.157</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"9f24678eb3854378a6393a0e7e3acce7"'>9f24678eb3854378a6393a0e7e3acce7</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 660/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 417.35</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by markusgustavssonking** [comment] 2019-07-09 07:17
Duplicate of #2654

**Closed by markusgustavssonking** 2019-07-09 07:17 UTC
