### ISSUE TITLE
Drag and drop file from finder to "builtins" folder in Assets panel (Flush is forbidden from target!)

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#2571] opened 2019-04-28 10:23 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-04-24T16:54:19.404579</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>61f46cee8040eb233ecc7e328f8b6d97693f1f40</td></tr>
<tr><td>Defold engine sha</td><td>e05232d70b8a6d8c69fcfe968f01b876090ffa06</td></tr>
<tr><td>Defold version</td><td>1.2.151</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"7fc5a62e85dc48b792b29c0b0ac18e7f"'>7fc5a62e85dc48b792b29c0b0ac18e7f</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 460 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-2.8.38</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.4</td></tr>
<table>

**Comment by matgis-king** [comment] 2019-04-29 07:55
JDK bug. Duplicate of #2438, #2315, #1948, #1874, and #1791.

**Closed by matgis-king** 2019-04-29 07:55 UTC
