### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GregBreinholt** [defold/editor2-issues#2601] opened 2019-05-15 09:14 UTC
### Expected behaviour
Connect to phone over IP

### Actual behaviour
Crash

### Steps to reproduce
Entered  IP shown on phone in the editor. Chose Build
<hr/>

<table>
<tr><td>Build time</td><td>2019-05-15T10:37:18.565297</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>cdbf588639f378d5a7659bdfcdd27e3fc7953b96</td></tr>
<tr><td>Defold engine sha</td><td>89a2b88bceb3b17682f301b2212764ea16761f4c</td></tr>
<tr><td>Defold version</td><td>1.2.153</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"2ca66e529f524785b290fb20284e6f08"'>2ca66e529f524785b290fb20284e6f08</a></td></tr>
<tr><td>GPU</td><td>GeForce RTX 2070 with Max-Q Design/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 430.64</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment] 2019-05-16 08:32
Duplicate of #2526. Unhelpful error message, but the underlying problem could be a network error or your game is in a busy loop not having time to respond.

**Closed by matgis-king** 2019-05-16 08:32 UTC
Labels: duplicate, unhelpful-error
