### ISSUE TITLE
Editing anything in the "Map" table in a .gamepads file deselects gamepad

### ISSUE THREAD

**Issue by dapetcu21** [defold/editor2-issues#2663] opened 2019-06-26 09:47 UTC
### Expected behaviour
The currently selected gamepad should remain selected after adding a new input mapping

### Actual behaviour
The view resets and I have to re-select the gamepad

### Steps to reproduce
In a .gamepads file, select a gamepad, then try to add another input mapping or change any property of any existing one.

<hr/>

<table>
<tr><td>Build time</td><td>2019-06-25T16:21:37.102998</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>39e92de4e2d97ab951ae10cfba7302bbaeec0d2f</td></tr>
<tr><td>Defold engine sha</td><td>d7042d5368c338ed5d66b6dff9c60a20924385ac</td></tr>
<tr><td>Defold version</td><td>1.2.157</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Plus Graphics 650</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.9.22</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.5</td></tr>
<table>

**Comment by markusgustavssonking** [comment] 2019-06-27 07:21
Duplicate of https://github.com/defold/editor2-issues/issues/2588
Closing.

**Closed by markusgustavssonking** 2019-06-27 07:21 UTC
Labels: duplicate
