### ISSUE TITLE
resizing window messes up relative go positions when rendering to texture.

### ISSUE THREAD

**Issue by needsnaming** [defold/editor2-issues#1057] opened 2017-07-10 08:28 UTC
### Expected behaviour
When resizing the game window, the rendered material should remain consistent. 

### Actual behaviour
When resizing the window parts of a game object, that I am rendering to texture, drastically change position in relation to their parent/siblings.

### Steps to reproduce

make a game object. with multiple sprites.
render to texture.
change screen size.

This is what my test scene looks like at launch.
The knight and everything behind him is normal. 
The black border image and the gradient bar are being rendered to texture.
![capture4](https://user-images.githubusercontent.com/1650079/28008873-7962a02e-6516-11e7-8dae-84c8d3ce6c58.PNG)

After resizing the window. The border image is a completely different scale. and the gradient image that is its sibling, did not change in the same way the border image changed. They are both part of the same game object. so I would assume they should both stay together in the same relative positions no matter how the screen is resized. 
![capture41](https://user-images.githubusercontent.com/1650079/28008911-aad643a4-6516-11e7-8c10-15b70628251f.PNG)

As you see here the hierarchy should be fixed and when one resize affects one object it should affect the other in the same way.
![capture42](https://user-images.githubusercontent.com/1650079/28009065-44c54ae6-6517-11e7-8f36-dea486e6f82c.PNG)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>6a36f46bbd1180851909b2f15171d22b502dd38e</td></tr>
<tr><td>Build time</td><td>2017-07-08T00:43:25.979550</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment] 2017-07-10 10:01
The scene graph (i.e. collection) is completely separate from the window size and unaffected by any resizes. (This is different in GUI scenes, which have features like 'anchoring' which need window size.) The transform from collection scene graph to draw calls (i.e. where things end up on screen) is completely defined by the render script and the shaders in use when rendering.
To debug your problem, I suggest you place "marker" sprites on the game objects you listed above, and these sprites should be rendered by the builtin materials. This way you can see which part of the render script and/or custom shaders that produce the diffs in screen positions. Do you use custom shaders? If so, a gotcha is that due to render-batching, the vertex streams are pretransformed. There should be comments about this in the builtin shaders.

**Comment by needsnaming** [comment] 2017-07-12 04:43
thanks, I'll read that. I'm probably just doing something really crazy that is not intended. Probably safe to just close this then.

**Comment by RagnarSvenssonKing** [comment] 2017-07-12 10:45
Closing this issue for now as it seems to be user-controlled. Please file a new issue if the problem seems to be caused by the engine.

**Closed by RagnarSvenssonKing** 2017-07-12 10:45 UTC
Labels: more-info
