### ISSUE TITLE
Editor exception: java.lang.OutOfMemoryError [DEFEDIT-1659] [DEFEDIT-1667]

### ISSUE THREAD

**Issue by dasannikov** [defold/editor2-issues#2549] opened 2019-04-10 11:58 UTC
Typical error in editor.

java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space

I have 8Gb RAM and Defold (Java) used 2.6Gb when crashed.

Useally crashed when i open many atlasses and collections (with different atlasses)

<table>
<tr><td>Build time</td><td>2019-04-04T11:50:51.981930</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ca8b423b50b0b3ed8b52d81fd7bf57a45b5e64f5</td></tr>
<tr><td>Defold engine sha</td><td>e79cdece4f5c8498302b3b00591808e3dc5a1827</td></tr>
<tr><td>Defold version</td><td>1.2.150</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"488a275d027f41648763efadf45613c9"'>488a275d027f41648763efadf45613c9</a></td></tr>
<tr><td>GPU</td><td>GeForce GT 640/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 391.91</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by matgis-king** [comment] 2019-04-11 10:19
We're investigating this. As a workaround, could you try adding `-Xmx4G,` like this to the beginning of the
```
vmargs = -Xmx4G,-Djna.nosys=true...
```
line in the `config` file next to the Defold executable?

This will increase the maximum memory the editor can access and allow you to work with your project. You might have to redo this if you update the editor until we can address this.

**Comment by dasannikov** [comment] 2019-04-11 10:40
Thx. It helps to working longer.
But I have reached 4Gb anyway :)

![Скриншот 2019-04-11 12 37 44](https://user-images.githubusercontent.com/1015770/55951194-f2164780-5c56-11e9-88fa-7ea52afe7c55.png)

**Comment by matgis-king** [comment] 2019-04-11 11:38
You can increase it further, probably even past how much ram you have. I think the only thing that will happen is that you'll get a different kind of error if the memory eventually runs out.

4 GB does sound like a lot though. I don't think even our most ambitious in-house projects use that much ram in the editor. Are you using a lot of very large atlases?

**Comment by dasannikov** [comment] 2019-04-11 12:35
You are added to this project (Called "AlphabetBase" in defold Dashboard) - It's animated alphabet for kids. I have many 4k atlases (fullscreen spine animations). Editor useally crash after ~20 atlases (open/close) and -30-40 when I set 4GB. 

In the new alphabet project I have 45 letters (~2 atlases per letter)

**Comment by matgis-king** [comment] 2019-04-12 08:06
Thanks for the information! We'll have to conduct an investigation about what is causing the memory usage to spike. Hopefully we can start looking into it next week.

**Comment by matgis-king** [comment] 2019-04-24 15:15
The cause seems to be the 4k atlases. The `.png` image files are tiny since they have large areas of homogenous color, which compresses very well. However, once we load these in the editor the raw pixel data will need to be decompressed. For example, each 2048 by 2048 pixel background image will decompress to 2048 x 2048 x 4 bytes = 16 MB, even though the `.png` file was only around 40 KB on disk.

Memory will start to fill up after you've opened a couple of scenes like this, since eventually all the uncompressed images from the project will reside in memory.

We've merged a partial fix to the editor that will try to free up some memory when we get near to the limit. Hopefully this will prevent the memory from running out. If you update the editor, you might still need to add the `-Xmx4G` flag in the config file. That will be addressed in 1.2.152, which should hopefully be released soon.

**Comment by AGulev** [comment] 2019-04-29 19:41
Solved in 1.2.152 
https://forum.defold.com/t/defold-1-2-152-has-been-released/50680

**Closed by AGulev** 2019-04-29 19:41 UTC
Labels: serious
