### ISSUE TITLE
Close others, caused "left" tab to be blank and broken.

### ISSUE THREAD

**Issue by adamwestman** [defold/editor2-issues#484] opened 2017-02-13 09:17 UTC
### Expected behaviour
I expect the other tabs to be closed and the one I asked to be untouched.

### Actual behaviour
The tab is left but broken.

### Steps to reproduce
Open a few tabs.
Right click and select "close others" on one.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.97</td></tr>
<tr><td>Defold sha</td><td>6724f8ac845b14b7a54a1305fbf93a34789f674b</td></tr>
<tr><td>Build time</td><td>2017-02-10T17:47:50.773801</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<table>

**Comment by ragnard-king** [comment] 2017-02-13 14:14
Duplicate of https://github.com/defold/editor2-issues/issues/364?

**Comment by adamwestman** [comment] 2017-02-14 00:05
Yeah, looks like it

**Comment by RagnarSvenssonKing** [comment] 2017-07-13 07:53
Fixed previously.

**Closed by RagnarSvenssonKing** 2017-07-13 07:53 UTC
Labels: duplicate, serious
