### ISSUE TITLE
Fails to run debug

### ISSUE THREAD

**Issue by polycursegames** [defold/editor2-issues#2642] opened 2019-06-11 19:11 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-06-11T09:19:24.991253</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4fe1a4135c842ac05bff8e1fc28884296052a3e2</td></tr>
<tr><td>Defold engine sha</td><td>67b68f1e1ac26a3385fb511cdce520fe52387bb0</td></tr>
<tr><td>Defold version</td><td>1.2.156</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"b97316644ea1454a91e69abcaf8939a5"'>b97316644ea1454a91e69abcaf8939a5</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro Vega 20 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-2.9.26</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.5</td></tr>
<table>

**Comment by markusgustavssonking** [comment] 2019-06-12 11:38
Duplicate of #2374

**Closed by markusgustavssonking** 2019-06-12 11:38 UTC
