### ISSUE TITLE
colorslide tutorial error when building

### ISSUE THREAD

**Issue by flashjaysan** [defold/editor2-issues#2633] opened 2019-06-07 08:31 UTC
### Expected behaviour
The build command should just run the game.
### Actual behaviour
When I tried to build the game, the error screen showed with the java.lang.NullPointerException: Unknown message. However, it worked corretly the second attempt.
### Steps to reproduce
Create a new project from the colorslide tutorial then use the Project > Build command.
<hr/>

<table>
<tr><td>Build time</td><td>2019-06-05T17:52:48.572452</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8810fea721c4bacdfa91ec47161f422795eb81a3</td></tr>
<tr><td>Defold engine sha</td><td>838cecd7a26c932e6be73421d98e51ba12f1d462</td></tr>
<tr><td>Defold version</td><td>1.2.155</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"e7618d7289d7487fa1c2dd0cada66064"'>e7618d7289d7487fa1c2dd0cada66064</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 960/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 416.34</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by matgis-king** [comment] 2019-06-10 07:43
Duplicate of #2632 with no additional info. Closing.

**Closed by matgis-king** 2019-06-10 07:43 UTC
Labels: duplicate, jdk, serious
