### ISSUE TITLE
Gui box nodes with children are not rendered correctly

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#570] opened 2017-03-08 19:15 UTC
### Expected behaviour
When I set a texture for a box node I expect to see it in the gui editor

### Actual behaviour
The texture that I set on a box node doesn't change or is drawn on the wrong box node

### Steps to reproduce
Create a root box node
Add a number of box nodes as children
Change textures for the different nodes
Notice that the textures that are selected in the properties view aren't the ones drawn in the gui scene editor
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.99</td></tr>
<tr><td>Defold sha</td><td>bf70ee4bff04e38c44e20bb6f60b4eaec4b971be</td></tr>
<tr><td>Build time</td><td>2017-03-07T10:01:03.171927</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment] 2017-07-13 07:30
Closing as unable to reproduce, it's likely it has been fixed previously but this issue was never updated.

**Closed by RagnarSvenssonKing** 2017-07-13 07:30 UTC
Labels: serious
