### ISSUE TITLE
some issue

### ISSUE THREAD

**Issue by 012rev3** [defold/editor2-issues#1100] opened 2017-08-07 09:47 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.110</td></tr>
<tr><td>Defold sha</td><td>f99ec13bc35396b0c5e77a2888962a8702e2fc55</td></tr>
<tr><td>Build time</td><td>2017-08-03T10:29:30.346216</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>x86</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=0b1df8867a48419792ae2e810b6b3159'>0b1df8867a48419792ae2e810b6b3159</a></td></tr>
<table>

**Comment by ragnard-king** [comment] 2017-08-07 11:13
Duplicate of #1099

**Comment by ragnard-king** [comment] 2017-08-11 09:23
This issue should be resolved in latest update.

**Closed by ragnard-king** 2017-08-11 09:23 UTC
Labels: blocker, duplicate
