### ISSUE TITLE
Scene picking does not work according to Z order [DEFEDIT-849]

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#560] opened 2017-03-07 13:55 UTC
STR:

- Create 2 game objects.
- Put one at Z=0 and one at Z=-1
- Make sure the one at Z=0 frames the one in front
- Try to pick the frontmost one

![screen shot 2017-03-07 at 14 53 22](https://cloud.githubusercontent.com/assets/65613/23659344/206e0256-0346-11e7-81b0-04367dddaaf9.png)

Note: Reversing Z positions on objects reveals that picking seems to sort Z backwards or something similar.

**Comment by Malmer** [comment] 2017-03-07 22:19
Duplicate of issue #187. My oldest unfixed issue :)

Made some comments on it how to solve it in a way that will more or less always give you the one you intended to click.

tldr; Always select the one with the smallest area under the cursor.

**Closed** 2017-03-15 09:05 UTC
Labels: blocker
