### ISSUE TITLE
android certificate and private key to make apk on this error

### ISSUE THREAD

**Issue by jonglae** [defold/editor2-issues#2681] opened 2019-07-10 05:33 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-07-09T15:50:23.313263</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d9c198fa66c19fe35dc2e5d01c460952a8808d7a</td></tr>
<tr><td>Defold engine sha</td><td>3d63d0509cc828c9555afc149cccfea0f7f83c97</td></tr>
<tr><td>Defold version</td><td>1.2.158</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"37fe4064fdcf4f7a8394d42fa5af0a71"'>37fe4064fdcf4f7a8394d42fa5af0a71</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1050/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 430.26</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.2.0-1-MANJARO</td></tr>
<table>

**Comment by markusgustavssonking** [comment] 2019-07-10 07:25
Duplicate of #2572

**Closed by markusgustavssonking** 2019-07-10 07:25 UTC
Labels: duplicate
