### ISSUE TITLE
Concurrent modification of graph on Close All from tab context menu

### ISSUE THREAD

**Issue by erikangelin-king** [defold/editor2-issues#1765] opened 2018-03-22 09:27 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td></td></tr>
<tr><td>Defold channel</td><td></td></tr>
<tr><td>Defold editor sha</td><td></td></tr>
<tr><td>Defold engine sha</td><td></td></tr>
<tr><td>Defold version</td><td>dev</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"4fdfa46888f6476ca92b7f3712bbaccb"'>4fdfa46888f6476ca92b7f3712bbaccb</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M290X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by erikangelin-king** [comment] 2018-03-22 09:28
This was from a dev branch though.

**Comment by matgis-king** [comment] 2018-04-03 12:42
Just tried this on `editor-dev` and couldn't reproduce it, even before defold/defold#2196 was merged. Maybe depends on project content? I think we need more detailed repro steps.

**Closed** 2018-11-27 13:55 UTC
Labels: blocker
