### ISSUE TITLE
java.lang.NullPointerException: Unknown | After fetch library

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2596] opened 2019-05-12 22:03 UTC
<hr/>

<table>
<tr><td>Build time</td><td>2019-05-07T09:51:47.616011</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>14212f327845c31295f296a33a1de5278836a85a</td></tr>
<tr><td>Defold engine sha</td><td>11b1e7662dd68172fca551c52cba248eea16a364</td></tr>
<tr><td>Defold version</td><td>1.2.152</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"94f8f51aa1564d3e8feec492a61dd541"'>94f8f51aa1564d3e8feec492a61dd541</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment] 2019-05-13 07:29
Duplicate of #2572 and #2590 with no additional info. Closing

**Closed by matgis-king** 2019-05-13 07:30 UTC
Labels: duplicate, jdk, serious
