### ISSUE TITLE
Draging a folder with images and atlases in it gives error [DEFEDIT-803]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#523] opened 2017-02-21 17:08 UTC
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>6725d7a9bc8fc85b3d6759eb5ed7dfb9df2cf9fb</td></tr>
<tr><td>Build time</td><td>2017-02-21T10:13:40.438078</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=a5fcd39c502b4fabb2c56cb8ec5f2877'>a5fcd39c502b4fabb2c56cb8ec5f2877</a></td></tr>
<table>

**Comment by matgis-king** [comment] 2017-02-22 12:55
I'm unable to reproduce this in `dev`. Here's what I did:
1. Created a new folder in my project.
2. Dragged some `.png` files to it from Finder.
3. Created an `.atlas` file in the folder and added the `.png` files to it.
4. Added a Sprite to a Game Object in my `main.collection` that referenced the `.atlas` file.
5. Moved the folder containing the `.atlas` and `.png` files in the Asset Brower panel.

I repeated step 5 several times, and every time the references to the `.atlas` and the `.png` files were updated to the new location. I did not manage to cause the error.

Am I missing a step?

**Comment by Malmer** [comment] 2017-02-22 13:12
I have been having lots of issues when moving folders in general in defold. Maybe it has to do with things being in collection proxies? But I got an error moving my images folder and moving my folder with collections and scripts. All of these folders do have multiple subfolders too.

**Comment by Malmer** [comment] 2017-02-22 13:17
My folder structure:

```
assets
  images
    atlas
      myaltas.atlas
    game
      items
        (a bunch of pngs)
```

Steps:
1. Create folder named "test"
2. Drag assets to folder tests
3. Error

**Comment by matgis-king** [comment] 2017-02-27 14:38
I'm still not able to reproduce this using the suggested folder structure inside the same project and editor revision. There must be an earlier step we're missing. I've added some asserts in a PR that might help us track down the cause.

**Comment by matgis-king** [comment] 2017-02-28 12:27
Asserts have been merged. Let's close this for now, and create a new issue if any of the asserts trigger.

**Closed by matgis-king** 2017-02-28 12:27 UTC
Labels: blocker, more-info
