### ISSUE TITLE
GUI Adjust Reference defaults to "Root (Deprecated)"

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#900] opened 2017-05-22 15:33 UTC
### Expected behaviour
Default to something that is not deprecated

### Actual behaviour
It defaults to deprecated.

### Steps to reproduce
Create a new GUI

<hr/>
Since this is deprecated, then maybe it should be removed from the list completely. Games still using the old adjust reference should have had time to fix this by now. 

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>d85dc7e615a04a574c0d772a914fe61b5c5f2dab</td></tr>
<tr><td>Build time</td><td>2017-05-18T15:29:25.374476</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment] 2017-06-22 12:16
Duplicate of https://github.com/defold/editor2-issues/issues/564 which has been fixed.

**Closed by ragnard-king** 2017-06-22 12:16 UTC
Labels: quick-win?, serious
