### ISSUE TITLE
GUI particlefx positions not updated correctly when resizing a window

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1544] opened 2017-12-31 21:06 UTC
Create some particles in gui, resize window, new particles generated are correct, old particles play out at the old scale/relative position

**Comment by britzl** [comment] 2018-08-23 11:51
Duplicate of https://github.com/defold/editor2-issues/issues/2069. Closing.

**Closed by britzl** 2018-08-23 11:51 UTC
Labels: engine
