### ISSUE TITLE
NPE When clicked on Project Button in Top Nav Menu

### ISSUE THREAD

**Issue by zugzug90** [defold/editor2-issues#2627] opened 2019-06-02 14:21 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-04-04T11:50:36.942743</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ca8b423b50b0b3ed8b52d81fd7bf57a45b5e64f5</td></tr>
<tr><td>Defold engine sha</td><td>e79cdece4f5c8498302b3b00591808e3dc5a1827</td></tr>
<tr><td>Defold version</td><td>1.2.150</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"cb88c94630304dc19e3f603f868b8c6f"'>cb88c94630304dc19e3f603f868b8c6f</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1050 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 384.130</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-50-generic</td></tr>
<table>

**Comment by matgis-king** [comment] 2019-06-03 08:24
```
javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7.class java.lang.NullPointerException: null
    at javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7(MenuButtonSkinBase.java:188)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by matgis-king** [comment] 2019-06-03 08:25
Duplicate of #2572 with no additional info. Closing.

**Closed by matgis-king** 2019-06-03 08:25 UTC
Labels: duplicate, jdk, serious
