### ISSUE TITLE
Tried to build and run the Movement tutorial.

### ISSUE THREAD

**Issue by flashjaysan** [defold/editor2-issues#2632] opened 2019-06-07 06:55 UTC
### Expected behaviour
The game should have launched.
### Actual behaviour
An error message appeared related to Java. I didn't have the time to note the exact message since it closed when I clicked the report button.
### Steps to reproduce
I just loaded a new Movement tutorial and tried to launch it for testing. The second time it worked so I'm not sure how to reproduce this.
<hr/>

<table>
<tr><td>Build time</td><td>2019-06-05T17:52:48.572452</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8810fea721c4bacdfa91ec47161f422795eb81a3</td></tr>
<tr><td>Defold engine sha</td><td>838cecd7a26c932e6be73421d98e51ba12f1d462</td></tr>
<tr><td>Defold version</td><td>1.2.155</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"8687108b14584947923b275974a0bfc9"'>8687108b14584947923b275974a0bfc9</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 960/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 416.34</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by matgis-king** [comment] 2019-06-10 07:42
```
javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7.class java.lang.NullPointerException: null
    at javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7(MenuButtonSkinBase.java:188)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by matgis-king** [comment] 2019-06-10 07:50
Duplicate of #2572 with no additional info.

**Closed by matgis-king** 2019-06-10 07:50 UTC
Labels: duplicate, jdk, serious
