### ISSUE TITLE
Unresponsive when deleting images from folder

### ISSUE THREAD

**Issue by ludd1** [defold/editor2-issues#632] opened 2017-03-30 08:27 UTC
### Expected behaviour
Atlas updates as images within it becomes unavailable, or displays error.
### Actual behaviour
Defold becomes unresponsive and will not work if the atlas containing the deleted images is opened.
### Steps to reproduce
Have an atlas with images in.
Open the atlas and have it open.
Delete a few of those images from your image folder.
Defold becomes unresponsive.

Close Defold and open it again.
Open the atlas. 
Defold is unresponsive
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.101</td></tr>
<tr><td>Defold sha</td><td>dc0d89c9290bfe0862c7e26be09d207b0b334197</td></tr>
<tr><td>Build time</td><td>2017-03-29T19:05:33.374598</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment] 2017-03-30 12:02
I believe the root cause is same as for https://github.com/defold/editor2-issues/issues/516. A fix is in being worked on.

**Closed** 2017-04-03 07:57 UTC
Labels: blocker, duplicate

**Comment by ragnard-king** [comment] 2017-04-03 08:02
Fixed coming in update today.
