### ISSUE TITLE
Option to close project and return to the launcher

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#661] opened 2017-04-11 17:05 UTC
This would be handy to have rather than needing to close Defold and reopen it.

File -> Close Project = goes back to launcher where another project can be opened

**Comment by AGulev** [comment] 2018-01-09 09:43
@subsoap @erikangelin-king I think it's a duplicate of https://github.com/defold/editor2-issues/issues/76

**Closed** 2018-01-09 09:44 UTC
Labels: feature
