### ISSUE TITLE
Null pointer exception with library dependency/gui

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#1184] opened 2017-09-06 06:58 UTC
- Added dirty larry library as project dependency
- created GUI
- created template from "checkbox_label"
- Boom

<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.112</td></tr>
<tr><td>Build time</td><td>2017-09-05T14:35:04.866814</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M370X OpenGL Engine</td></tr>
<tr><td>Defold sha</td><td>35eb95060f19cafccf910239e4243801a3a47118</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=fdafeb44ab854c3a9a6e229ad1739213'>fdafeb44ab854c3a9a6e229ad1739213</a></td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by matgis-king** [comment] 2017-09-07 08:11
I wasn't able to reproduce this. I tried adding a Template using the `checkbox_label` scene to a regular gui scene, a gui scene that was itself used as a Template and a gui scene that was used by a Game Object inside a Collection, but never got the exception.

From the callstack it looks like a gui scene had a non-number for its Max Nodes property, but it looks like the scenes in Dirty Larry all have valid Max Nodes, and I wasn't able to enter a bad value for Max Nodes in my own gui scenes.

Do you have any ideas what could have happened?

**Comment by matgis-king** [comment] 2017-10-10 08:09
Closing this for now as I am unable to reproduce it in recent builds.

**Closed by matgis-king** 2017-10-10 08:09 UTC
Labels: blocker, more-info
