### ISSUE TITLE
Error when trying to build our big project

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#380] opened 2017-01-10 17:00 UTC
<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>521126d4d571631bab3f5467bb5f960ada3e1be1</td></tr>
<tr><td>Build time</td><td>2017-01-10T15:33:23.557784</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.2</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=a8b8e9b46ec94200bdb4ef613370c21d'>a8b8e9b46ec94200bdb4ef613370c21d</a></td></tr>
<table>

**Comment by Malmer** [comment] 2017-01-18 07:26
I don't get this anymore, but the error may still exist, depending on what was the cause of it.

**Comment by ragnard-king** [comment] 2017-01-18 07:31
This was likely caused by the project having a spine node in a GUI scene, for which editor2 support was merged 6 days ago, so closing. Thanks for commenting!

**Closed by ragnard-king** 2017-01-18 07:31 UTC
Labels: blocker
