### ISSUE TITLE
iOs bundle without engine

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1045] opened 2017-07-01 07:41 UTC
When I try to bundle ios application with native extension, i recieve a small ipa without engine:
![2017-07-01_10-39-12](https://user-images.githubusercontent.com/2209596/27760175-ac900a78-5e49-11e7-9151-01f4a8e19114.png)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>2b46a7e2dcee415d080f7d275d113890f017c965</td></tr>
<tr><td>Build time</td><td>2017-06-30T18:08:14.612210</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by mathiaswking** [comment] 2017-07-12 09:16
Could not reproduce locally, and user doesn't experience the issue anymore either.
Closing issue for now.

**Comment by AGulev** [comment] 2017-07-24 11:32
@mathiaswking bug reproduce again
Can I provide something for help to investigate it?

**Comment by AGulev** [comment] 2017-07-24 11:41
archive with editor's log folder right after build
https://yadi.sk/d/2YGLQt9I3LLykN

**Comment by AGulev** [comment] 2017-07-24 11:56
same bug without NE

**Comment by AGulev** [comment] 2017-07-24 13:37
I tred to reinstall editor2, remove build folder, restart mac - I can't build ipa

**Comment by Lerg** [comment] 2017-07-24 13:46
I have the same problem now.

**Comment by AGulev** [comment] 2017-07-24 14:15
I just checked, bug reproduce only in editor 2

**Comment by mathiaswking** [comment] 2017-07-25 08:11
Thx for the feedback, it's good to know that doesn't have anything to do with NE at least. But unfortunately, I still cannot reproduce it.

Both editors use bob.jar to bundle, so I would have expected the issue to be in both editors. Unfortunately, the Editor 2 people are on vacation until next week.

**Comment by AGulev** [comment] 2017-07-25 08:14
Strange, but it works fine again for me after yesterday updates.

**Comment by matgis-king** [comment] 2017-08-23 07:56
Duplicate of fixed issue #1091.

**Closed by matgis-king** 2017-08-23 07:56 UTC
Labels: blocker
