### ISSUE TITLE
little error with no visible consquence

### ISSUE THREAD

**Issue by YaziidK** [defold/editor2-issues#2801] opened 2019-10-19 15:39 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-09-16T10:18:30.370777</td></tr>
<tr><td>Defold channel</td><td>stable</td></tr>
<tr><td>Defold editor sha</td><td>e07f3bb9e8c970eceda8dce8efd5905fd67fa720</td></tr>
<tr><td>Defold engine sha</td><td>e07f3bb9e8c970eceda8dce8efd5905fd67fa720</td></tr>
<tr><td>Defold version</td><td>1.2.162</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"f2fb3e67a26241cfa5d66aea0dba8399"'>f2fb3e67a26241cfa5d66aea0dba8399</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) Ivybridge Mobile </td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 19.0.8</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.0.0-32-generic</td></tr>
<table>

**Comment by matgis-king** [comment] 2019-10-22 09:30
Closing as duplicate of #2692 with no additional info.

**Closed by matgis-king** 2019-10-22 09:30 UTC
Labels: duplicate, jdk, serious
