### ISSUE TITLE
NPE when switching tabs (from script to collection)

### ISSUE THREAD

**Issue by JCash** [defold/editor2-issues#2717] opened 2019-08-25 09:08 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-08-20T15:05:19.435099</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d1f9e4839758a031a2a76842d91a2cdee9f90a76</td></tr>
<tr><td>Defold engine sha</td><td>1a8e53ae9c38a09b742d38dffc6a9f2efdbe6e97</td></tr>
<tr><td>Defold version</td><td>1.2.160</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"461bc95dd9e5491ebe708946746e36a1"'>461bc95dd9e5491ebe708946746e36a1</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 650</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.8.38</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.4</td></tr>
<table>

**Comment by vlaaad** [comment] 2019-08-26 08:59
Duplicate of #2692

**Closed by vlaaad** 2019-08-26 08:59 UTC
