### ISSUE TITLE
clojure.lang.ExceptionInfo: SCHEMA-VALIDATION

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#429] opened 2017-01-25 13:21 UTC
1. Open game.project
2. Focus in the main collection field in bootstrap section
3. Press Enter while in the path field for main collection

Actual result: 
clojure.lang.ExceptionInfo: SCHEMA-VALIDATION

Doesnt matter what value you have as main path.

![schema1](https://cloud.githubusercontent.com/assets/22887289/22292003/895090f2-e309-11e6-9ab8-7ac67e649d18.gif)

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>f32230d96b986616b742218d7f1a5bce26519b2e</td></tr>
<tr><td>Build time</td><td>2017-01-24T18:27:02.669047</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=fdcba1f93bb14b858de30b6e13700a51'>fdcba1f93bb14b858de30b6e13700a51</a></td></tr>
<table>

**Comment by ragnard-king** [comment] 2017-01-25 13:28
Duplicate of #406.

**Comment by erikangelin-king** [comment] 2017-05-18 09:39
Can't repro

**Closed by erikangelin-king** 2017-05-18 09:39 UTC
Labels: duplicate
