### ISSUE TITLE
Defold Editor (x64) crashing unexpectedly

### ISSUE THREAD

**Issue by Serious-Table** [defold/editor2-issues#2118] opened 2018-08-11 06:07 UTC
It's been hard to pinpoint the root cause, as it's been inconsistent, but at present I've been able to get it crash after doing the following:

* While following the War Battles Tutorial in the "Other Pane"
* Open tank.go
* Add a Box Shape to collisionobject
* Editor crashes shortly after

I've been able to save it before the crash, and upon opening after the save, the Box is still present.

I've attached the log
[hs_err_pid2088.log](https://github.com/defold/editor2-issues/files/2279963/hs_err_pid2088.log)

I'm really eager to learn and use Defold, and have enjoyed using it thus far, but the crashing is really deterring me from continuing. If I can get a solution, I'll be on board.

**Comment by Serious-Table** [comment] 2018-08-11 06:46
It may be worth noting that I had the following drivers on an AMD RX 580:

18.7.1 - Crash
18.8.1 - Same Crash

I've since rolled back to 18.5.1 (considered Stable, I believe) with a clean uninstall and reinstall, and so far no crashes trying to reproduce the steps above. Does that mean this is just a driver issue?

**Comment by Nougatos** [comment] 2018-08-12 01:10
I had similar crash :
* While following the War Battles Tutorial on step 2 "Add the map to the game".
* Open "main/main.collection".
* Right click on "Collection"  select "Add game object".
* When you put your mouse on "main.collection" panel (
panel at center of software) : and suddenly a crash !

I've attached the log.
[hs_err_pid14252.log](https://github.com/defold/editor2-issues/files/2280647/hs_err_pid14252.log)

Thanks to @Serious-Table for the solution.
Downgrade AMD driver works perfectly.

**Comment by erikangelin-king** [comment] 2018-11-06 14:51
Hi @Serious-Table and @Nougatos! We found one issue near this crash, can you try and upgrade your drivers and see if it still crashes?

**Comment by Serious-Table** [comment] 2018-11-14 05:33
> 
> 
> Hi @Serious-Table and @Nougatos! We found one issue near this crash, can you try and upgrade your drivers and see if it still crashes?

I'm currently on 18.11.1, the most updated version of Radeon graphics. I'm now crashing at a different point.

* Open a New Project with "Desktop Project"
* Open Main.Collection
* Right click on the game object nested under the collection in the Outline, named "go".
* Crash instantly.

If I do this in an empty project, it does not crash. If I expand the game object, then right click, it does not crash.

I don't know if they're related to the graphics driver, but figured I'd bring it up here. I'll let you know if replicating the same steps in this bug generates the same issue.

**Comment by erikangelin-king** [comment] 2018-11-14 05:56
Thanks! Can you attach the hserr_pid???.log file from this crash?

**Comment by Serious-Table** [comment] 2018-11-14 05:58
[hs_err_pid54408.log](https://github.com/defold/editor2-issues/files/2579342/hs_err_pid54408.log)
The most recent error log. This was from right clicking the game object in Main.collection in order to delete it during normal use.

**Comment by Serious-Table** [comment] 2018-11-15 01:03
@erikangelin-king New logs have been emailed, per your request!

**Comment by karlhenselin** [comment] 2018-12-21 13:07
I am having the same issue with a Radeon 7870 and the 12.2 drivers. Any resolution on this besides going back to the 5.2 drivers?
[gldebug.log](https://github.com/defold/editor2-issues/files/2702849/gldebug.log)
[hs_err_pid928.log](https://github.com/defold/editor2-issues/files/2702850/hs_err_pid928.log)

**Comment by Awasaky** [comment] 2019-01-05 10:04
[hs_err_pid2504.log](https://github.com/defold/editor2-issues/files/2729391/hs_err_pid2504.log)
Same problem - crashing with Radeon RX470, Windows 10. I tried all things like disable antivirus, admin rights, update and roll back drivers, update jre and jdk.
My crash way is - open editor, start sidescroller tutorial, at step select animation "bonus_star" it crash always, if editor window size changed or maximized. If I don't resize and don't maximize window it work fine.
But I can't use only 1/4 from screen to work with Defold.

**Comment by sthamilton** [comment] 2019-01-12 06:54
Changing my jre in the config file seems to have fixed my issue as well, running on latest AMD drivers. Now using jre1.8.0_131.

**Comment by erikangelin-king** [comment] 2019-02-20 16:35
We believe this was all caused by us still using the old GL_SELECT mode for selection, and we just merged a replacement. Please update and check if it helps!

**Closed** 2019-03-18 10:37 UTC
Labels: more-info, serious
