### ISSUE TITLE
Atlas size changing problems

### ISSUE THREAD

**Issue by tobi9** [defold/editor2-issues#946] opened 2017-05-28 16:49 UTC
I can't change the size of my images in the atlas it doesn't change( defold editor 2)
i think it is a bug if it's not how do I do it .

**Comment by ragnard-king** [comment] 2017-05-29 10:07
Hi @tobi9,

Thanks for the report, however I can't reproduce the problem -- maybe I'm misunderstanding what the issue is.

Can you explain a bit more about what you are trying to do and the steps you are taking?

**Comment by tobi9** [comment] 2017-05-29 23:43
When I tried to reduce the size of the images in the atlas in the properties panel the values did not change.

**Comment by ragnard-king** [comment] 2017-05-30 07:28
Ok, I understand. Unfortunately, resizing images is not something that you can do in the editor. The editor simply arranges a set of existing images into an atlas in an optimal manner. To resize an image you need to resize the source image in an image manipulation program. However, if you resize an image that is part of an atlas, then switch back to the editor, you should immediately see the updated image in the atlas (and everywhere else it is used). The size shown in the properties view is only there as a piece of helpful information, and that's why it's read-only.

I hope that makes sense. Closing this issue as it is working as intended. Feel free to re-open if you have any further questions.

**Closed by ragnard-king** 2017-05-30 07:28 UTC
Labels: more-info
