### ISSUE TITLE
ParticleFX properties panel can freeze up

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#906] opened 2017-05-23 03:50 UTC
Although it may just be to do with the curve editor etc. bugging out occasionally
![2017-05-22 20_49_26-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26337775/33272118-3f30-11e7-8a88-855313f1a798.png)

When they become stuck clicking on them doesn't do anything.

Actually it's the entire panel that can become frozen and requires editor restart to fix.

**Comment by RagnarSvenssonKing** [comment] 2017-05-24 06:51
Any other info you can think of to help us reproduce? Has it happened several times?

**Comment by subsoap** [comment] 2017-05-24 08:56
I'll be using the particle fx editor more soon and if I can get it to reproduce I will say.

**Comment by ragnard-king** [comment] 2017-05-30 13:37
@subsoap Has this happened again since your last comment?

**Comment by RagnarSvenssonKing** [comment] 2017-07-12 12:56
Closing this for now in lack of repro case. Please file a new issue if it happens again!

**Closed by RagnarSvenssonKing** 2017-07-12 12:56 UTC
Labels: blocker, more-info
