### ISSUE TITLE
File dragging prompts error.

### ISSUE THREAD

**Issue by Artechz** [defold/editor2-issues#2759] opened 2019-09-27 09:48 UTC
### Expected behaviour
File dragged to editor window to appear on the file tree.

### Actual behaviour
Error prompted and didn't add the file.

### Steps to reproduce
Drag a file to the editor window from Finder.

<hr/>

<table>
<tr><td>Build time</td><td>2019-09-17T10:58:53.532477</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b79253082f9f84b6b119d5246367abf540aed3a4</td></tr>
<tr><td>Defold engine sha</td><td>e07f3bb9e8c970eceda8dce8efd5905fd67fa720</td></tr>
<tr><td>Defold version</td><td>1.2.162</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"58d3438d13e34f4fa5ca120b73f1ffb7"'>58d3438d13e34f4fa5ca120b73f1ffb7</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Plus Graphics 655</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.4.7</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.3</td></tr>
<table>

**Comment by matgis-king** [comment] 2019-09-30 07:58
Duplicate of #1948 with no additional information.

**Closed by matgis-king** 2019-09-30 07:58 UTC
