### ISSUE TITLE
java.lang.NullPointerException: Unknown when syncing

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#446] opened 2017-02-01 14:18 UTC
I started the tutorial in the morning
The editor was left on during the day
Changed networks a few times, ethernet to wifi and back
Continued the tutorial in the afternoon
Saved regularly 
But i only synced one time when I was finished.
Pull and pushed all changes
When sync was done this error showed up

Actual result:
java.lang.NullPointerException: Unknown

Couldnt reproduce

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>d609ecceb5a9cb77f11597e834e9d3faa197c5c9</td></tr>
<tr><td>Build time</td><td>2017-01-31T17:37:34.819629</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=51485b75d74c40b094e9b4d9cd8549cc'>51485b75d74c40b094e9b4d9cd8549cc</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment] 2017-07-13 07:58
Closed as unable to reproduce.

**Closed by RagnarSvenssonKing** 2017-07-13 07:58 UTC
Labels: serious
