### ISSUE TITLE
Error adding a collection file to same collection

### ISSUE THREAD

**Issue by divait** [defold/editor2-issues#1235] opened 2017-09-26 21:13 UTC
### Expected behaviour
Show action no posible or not allowed
### Actual behaviour
The program get stuck and didn't add the collection file or show a non permited action, thows error Stackoverflow
### Steps to reproduce
open a collection file
on outline right click the main element
click add collection
select the same collection file
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.114</td></tr>
<tr><td>Defold sha</td><td>de362140b079dcade1daffb2d47a8caddf80ff47</td></tr>
<tr><td>Build time</td><td>2017-09-21T16:18:58.933590</td></tr>
<tr><td>OS name</td><td>Windows 8.1</td></tr>
<tr><td>OS version</td><td>6.3</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 520</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 21.20.16.4678</td></tr>
<table>

**Comment by ragnard-king** [comment] 2017-09-27 07:10
Thanks for the report! Duplicate of https://github.com/defold/editor2-issues/issues/140

**Closed** 2017-09-28 08:03 UTC
Labels: duplicate
