### ISSUE TITLE
I delete build directory from project and editor crushed every start

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#480] opened 2017-02-11 18:46 UTC
### Expected behaviour
Start editor
### Actual behaviour
Crush after open project
### Steps to reproduce
Delete folder build from project
log
[log_send3.txt](https://github.com/defold/editor2-issues/files/768815/log_send3.txt)

I want make full rebuild :) Because editor not apply my script for strange cause

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.97</td></tr>
<tr><td>Defold sha</td><td>6724f8ac845b14b7a54a1305fbf93a34789f674b</td></tr>
<tr><td>Build time</td><td>2017-02-10T17:47:50.773801</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by tarnumius** [comment] 2017-02-13 22:18
I make investigation and find problem. Problem was not in delete build folder.

Steps to reproduce:
1. I make folder MainMENU and add some components in folder and some GO
2. After I rename folder in MainMenu with external file namager (not in editor, because Editor say - cannot rename because same name exist)
3. Result - Editor cannot find folder MainMENU and crush.

After I corret paths inGO and project open.

**Comment by ragnard-king** [comment] 2017-10-03 07:11
Closing this as we've made lots of improvements in this area since this was reported, and I couldn't reproduce this. Feel free to re-open if the error persists. Thanks for the report!

**Closed by ragnard-king** 2017-10-03 07:11 UTC
Labels: serious
