### ISSUE TITLE
texture listing use counter-intuitive sorting, or rather no sorting at all

### ISSUE THREAD

**Issue by dodspunkare** [defold/editor2-issues#1027] opened 2017-06-25 19:59 UTC
### Expected behaviour
Textures in atlas sorted alphabetically.

### Actual behaviour
Textures in atlas sorted in the order they were added.

It's quite annoying to find specific textures if I have a million icons in my atlas.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.107</td></tr>
<tr><td>Defold sha</td><td>86632bf7cdeb8d9833baff3864fe480c1162f8da</td></tr>
<tr><td>Build time</td><td>2017-06-22T10:48:42.692440</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment] 2017-06-26 07:52
Duplicate of #717

**Comment by matgis-king** [comment] 2017-06-28 09:08
With defold/defold#1641 the list will be sorted!

**Closed by matgis-king** 2017-06-28 09:08 UTC
Labels: duplicate
