### ISSUE TITLE
NPE Changing collision map file in a tilesource [DEFEDIT-805]

### ISSUE THREAD

**Issue by GaussX** [defold/editor2-issues#525] opened 2017-02-22 11:52 UTC
### Expected behaviour
NPE Changing collision map file in a tilesource 
### Actual behaviour
java.lang.NullPointerException: Unknown
### Steps to reproduce
Try to change collision map file in a working tilesource(image+collision)
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>2487d36ec8de09c4519a5bf5a5be5b95bf332834</td></tr>
<tr><td>Build time</td><td>2017-02-22T10:45:24.591928</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=0deae11d1b91474aa391e1c1a6eb46a5'>0deae11d1b91474aa391e1c1a6eb46a5</a></td></tr>
<table>

**Comment by erikangelin-king** [comment] 2017-02-22 14:39
We recently merged a fix for a related issue and now I can't repro this, feel free to reopen this issue if it is still broken after you've installed the next update.

**Comment by GaussX** [comment] 2017-02-23 07:37
still broken

**Comment by erikangelin-king** [comment] 2017-02-23 08:22
Hmm. Could you send me (erik.angelin@king.com) a zip of your project, or just the minimal parts needed to repro? Also, can you check version, sha1 and date from Help > About?
Thanks!

**Comment by erikangelin-king** [comment] 2017-02-23 13:10
Thanks for the sample project, I can now repro the issue. Looking into this.

**Comment by erikangelin-king** [comment] 2017-02-23 13:48
Aha. The problem is that tiles128.png doesn't have an alpha channel, and we use that to calculate convex hulls. We will sadly have to prioritise other issues right now, but at least you can work around the problem by adding an alpha. Thanks again!

**Comment by erikangelin-king** [comment] 2017-03-20 10:31
Closing as duplicate, see https://github.com/defold/editor2-issues/issues/500

**Closed by erikangelin-king** 2017-03-20 10:31 UTC
Labels: duplicate, serious
