### ISSUE TITLE
When save my project

### ISSUE THREAD

**Issue by QkyGames** [defold/editor2-issues#994] opened 2017-06-09 19:23 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.106</td></tr>
<tr><td>Defold sha</td><td>2c1eba2a0fca3cb7e363c235d0721923337ba1ce</td></tr>
<tr><td>Build time</td><td>2017-06-09T15:53:44.894377</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=b55000d8e46d485299e0ca4d38aba23d'>b55000d8e46d485299e0ca4d38aba23d</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment] 2017-07-21 14:44
Closed as unable to reproduce

**Closed by RagnarSvenssonKing** 2017-07-21 14:44 UTC
Labels: blocker
