### ISSUE TITLE
when opening main.collection

### ISSUE THREAD

**Issue by puriin** [defold/editor2-issues#1850] opened 2018-04-30 01:36 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-04-25T17:00:59.765659</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>66a1a1cc9a785b62cb189fdc9c786e0690c6439d</td></tr>
<tr><td>Defold engine sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold version</td><td>1.2.126</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"100110e423384166897b53a9bf5cd6c4"'>100110e423384166897b53a9bf5cd6c4</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 620</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 21.20.16.4534</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment] 2018-04-30 06:57
This is a pretty common error that we're having trouble reproducing. Was this the first error you got? Did you recently update the editor? Did you run multiple editors side by side?
Does it still happen if you restart the editor?

**Comment by puriin** [comment] 2018-04-30 07:31
this was the second error, when I open the project I immediately build the
game then suddenly an error occured. I tried opening the main.collection
then this error occurred. This was the only project that I opened. When I
restart the editor there was no more errors.

I was also just wondering, there are times that I happened to misclick to
attach the collection file to itself then suddenly hanging and crashing.
For example i was trying to put collectionA.collection to
collectionB.collection but during the process I misclicked the
collisionB.collection then it hanged then I forced close it

**Comment by erikangelin-king** [comment] 2018-04-30 07:37
Alright, thanks! For some reason, we sometimes fail to load the native library used for texture compression. Did you update the editor just before this happened?

About the collections, that error has been reported in several variations and we're working on a general solution for handling dependency cycles in the project.

**Comment by puriin** [comment] 2018-04-30 07:38
I didn't update the editor before building

**Comment by erikangelin-king** [comment] 2018-04-30 07:43
Ok! If this happens again, feel free to open a new issue or write a note here!

**Comment by markusgustavssonking** [comment] 2019-06-03 06:50
This should be fixed since we changed how native libraries are loaded on Windows.

**Closed by markusgustavssonking** 2019-06-03 06:50 UTC
Labels: serious
