### ISSUE TITLE
Keyboard shortcut ctrl+x

### ISSUE THREAD

**Issue by Mefjus** [defold/editor2-issues#2846] opened 2019-11-22 21:02 UTC
I am very irritated by the fact that ctrl + x is able to cut the selected text but should also **be able to cut the entire line of code** when the cursor is on it.

**Comment by britzl** [comment] 2019-11-27 06:33
Duplicate of https://github.com/defold/editor2-issues/issues/1507

**Closed by britzl** 2019-11-27 06:33 UTC
