### ISSUE TITLE
Gets java.lang.NullPointerException: Unknown when trying to build an iOS application

### ISSUE THREAD

**Issue by the1schwartz** [defold/editor2-issues#1039] opened 2017-06-29 12:12 UTC
### Expected behaviour
Build iOS application

### Actual behaviour
Gets java.lang.NullPointerException: Unknown when trying to build an iOS application
No build errors shows up

### Steps to reproduce
Open attached project
Click Project -> Bundle -> iOS application...

[GA-SDK-DEFOLD-DEV.zip](https://github.com/defold/editor2-issues/files/1111952/GA-SDK-DEFOLD-DEV.zip)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>61272af994373ffbc4ffbfbd3b9a4aca3042fdde</td></tr>
<tr><td>Build time</td><td>2017-06-29T11:02:04.316185</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=4e9e9a69858b4ee68eb8ed75111b0c97'>4e9e9a69858b4ee68eb8ed75111b0c97</a></td></tr>
<table>

**Comment by mathiaswking** [comment] 2017-07-12 08:48
Hi @the1schwartz!

Unfortunately, I could not reproduce this issue (I used your project to test with).
I'm closing this particular issue, but please create a new one if the problem remains!
(That way we'll get more usable info from the reporting system)

**Closed by mathiaswking** 2017-07-12 08:48 UTC
Labels: blocker
