### ISSUE TITLE
Play on Linux Elementary OS

### ISSUE THREAD

**Issue by ReydVires** [defold/editor2-issues#2167] opened 2018-09-01 01:07 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-08-31T14:36:39.776742</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>fff392c8eeb27510d5400abab53cbae48509865d</td></tr>
<tr><td>Defold engine sha</td><td>1b90c9a905d634b766b467e3536458b9210ec812</td></tr>
<tr><td>Defold version</td><td>1.2.135</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"cff9689696a5473785f57ebf6f4cbcc1"'>cff9689696a5473785f57ebf6f4cbcc1</a></td></tr>
<tr><td>GPU</td><td>AMD KABINI (DRM 2.50.0 / 4.13.0-32-generic, LLVM 5.0.0)</td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 17.2.8</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.13.0-32-generic</td></tr>
<table>

**Comment by matgis-king** [comment] 2018-09-03 09:00
Duplicate of #1727. See there for a potential fix. Closing this one, but feel free to reopen if you think I was too hasty!

**Closed by matgis-king** 2018-09-03 09:00 UTC
Labels: duplicate
