### ISSUE TITLE
Minor error on Shadertoy Sample 

### ISSUE THREAD

**Issue by rpersaud** [defold/editor2-issues#2694] opened 2019-08-01 08:07 UTC
### Expected behaviour
Click on project to build

### Actual behaviour
Dialog with error, dismissed, clicked on project menu again to build, and it worked

### Steps to reproduce
Closed defold. Opened app. Clicked new. built new project from shadertoy sample. Clicked on project initially.

<hr/>

<table>
<tr><td>Build time</td><td>2019-07-30T16:50:09.989230</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5dd02a32a775ec61aac42fdf2b2e7a03cd0c6d68</td></tr>
<tr><td>Defold engine sha</td><td>f7d0a1ba6940e42c7f7e1c208ba484c3c34a135d</td></tr>
<tr><td>Defold version</td><td>1.2.159</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"4175926265e547d89326d9a0e4156ce6"'>4175926265e547d89326d9a0e4156ce6</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 750 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 430.86</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment] 2019-08-05 08:00
Closing as duplicate of #2693.

**Closed by matgis-king** 2019-08-05 08:00 UTC
Labels: duplicate
