### ISSUE TITLE
Collision object was removed after a few cancelled and successfull syncs

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#273] opened 2016-12-07 13:18 UTC
[Uploading editor2 - Copy.txt…]()

1. Have a game object and a spinemodel, the frog from getting started tutorial.
2. Save
3. Add a collision object to the game object
4. Add box and sphere shape
5. Put the shapes in a good place
6. Click sync, cancel, sync, cancel
7. Save all
8. Sync
9. Commit all changed files
10. Look at the game object

Actual result: The collision object is missing from the frog game object
Saw this in the log (which is attached)
org.eclipse.jgit.api.errors.JGitInternalException: Stashing local changes did not successfully complete

Defold version: 1.2.95
Defold sha: 7ca47a7f7aa0e4809e31ab2274fd1693a1fc5a7e
Platform: Windows 7 6.1 (x86)
Java version: 1.8.0_102-b14

**Comment by alexandru-p** [comment] 2016-12-07 13:23
Same issue occurred after only after one sync attempt (File > Sync > Cancel) on Windows 10 x64 
Defold version: 1.2.95
Defold sha: 7ca47a7f7aa0e4809e31ab2274fd1693a1fc5a7e

**Comment by matgis-king** [comment] 2016-12-07 14:07
I believe the Git stash and unstash at the start of the sync process is the likely culprit. If you modify a file, save it, then do some more changes that you don't save before going into the sync dialog, the stash and unstash will flag the file as externally changed. The editor will reload it from disk and you'll lose the unsaved changes.

The steps to reproduce are accurate up to step 6. You only need to go into the Synchronize dialog and cancel it once for the in-memory representation of the frog to be reverted to the last time you saved. However, the bug is possibly masked by the fact that reloaded resources get disconnected from any open tabs that show them (#165).

Note that this bug will likely be fixed by saving the project before starting the sync process (#215).

**Comment by RagnarSvenssonKing** [comment] 2016-12-08 09:01
First fix to remove the urgent aspect is to auto-save-all when syncing the files. We can look at fancy fixes later.

**Comment by matgis-king** [comment] 2017-01-05 10:28
Closing this since we now save the project before initiating the sync process.

**Closed by matgis-king** 2017-01-05 10:28 UTC
Labels: blocker
