### ISSUE TITLE
Error when editing a script, Nullpointer

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#178] opened 2016-11-11 10:54 UTC
{:cause nil,
 :via
 [{:type java.lang.NullPointerException,
   :message nil,
   :at [javafx.scene.Node localToScene "Node.java" 4340]}],
 :trace
 [[javafx.scene.Node localToScene "Node.java" 4340]
  [com.defold.editor.eclipse.DefoldStyledTextSkin getCaretLocation "DefoldStyledTextSkin.java" 413]
  [com.defold.editor.eclipse.DefoldStyledTextSkin$2 changed "DefoldStyledTextSkin.java" 156]
  [com.defold.editor.eclipse.DefoldStyledTextSkin$2 changed "DefoldStyledTextSkin.java" 107]
  [com.sun.javafx.binding.ExpressionHelper$SingleChange fireValueChangedEvent "ExpressionHelper.java" 182]
  [com.sun.javafx.binding.ExpressionHelper fireValueChangedEvent "ExpressionHelper.java" 81]
  [javafx.beans.property.IntegerPropertyBase fireValueChangedEvent "IntegerPropertyBase.java" 106]
  [javafx.beans.property.IntegerPropertyBase markInvalid "IntegerPropertyBase.java" 113]
  [javafx.beans.property.IntegerPropertyBase set "IntegerPropertyBase.java" 147]
  [com.defold.editor.eclipse.DefoldStyledTextArea setCaretOffset "DefoldStyledTextArea.java" 246]
  [com.defold.editor.eclipse.DefoldStyledTextArea impl_setCaretOffset "DefoldStyledTextArea.java" 270]
  [editor.code_view$fn__17488 invokeStatic "code_view.clj" 288]
  [editor.code_view$fn__17488 invoke "code_view.clj" 284]
  [editor.code_view_ux$fn__13485$G__13480__13494 invoke "code_view_ux.clj" 18]
  [editor.code_view$source_viewer_set_caret_BANG_ invokeStatic "code_view.clj" 447]
  [editor.code_view$fn__17734 invokeStatic "code_view.clj" 478]
  [editor.code_view$fn__17734 invoke "code_view.clj" 478]
  [editor.code_view_ux$fn__13485$G__13480__13494 invoke "code_view_ux.clj" 18]
  [editor.code_view_ux$right invokeStatic "code_view_ux.clj" 388]
  [editor.code_view_ux$fn__14315$fnk14313_positional__14316 invoke "code_view_ux.clj" 421]
  [editor.code_view_ux$fn__14315$fnk14313__14327$fn__14328 invoke "code_view_ux.clj" 421]
  [editor.code_view_ux$fn__14315$fnk14313__14327 invoke "code_view_ux.clj" 421]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 29]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [editor.handler$invoke_fnk invokeStatic "handler.clj" 45]
  [editor.handler$run invokeStatic "handler.clj" 65]
  [editor.code_view_ux$handler_run invokeStatic "code_view_ux.clj" 272]
  [editor.code_view_ux$handle_key_pressed invokeStatic "code_view_ux.clj" 281]
  [editor.code_view$setup_source_viewer$reify__17515 handle "code_view.clj" 375]
  [com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord handleBubblingEvent "CompositeEventHandler.java" 218]
  [com.sun.javafx.event.CompositeEventHandler dispatchBubblingEvent "CompositeEventHandler.java" 80]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 238]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 191]
  [com.sun.javafx.event.CompositeEventDispatcher dispatchBubblingEvent "CompositeEventDispatcher.java" 59]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 58]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.EventUtil fireEventImpl "EventUtil.java" 74]
  [com.sun.javafx.event.EventUtil fireEvent "EventUtil.java" 54]
  [javafx.event.Event fireEvent "Event.java" 198]
  [javafx.scene.Scene$KeyHandler process "Scene.java" 3964]
  [javafx.scene.Scene$KeyHandler access$1800 "Scene.java" 3910]
  [javafx.scene.Scene impl_processKeyEvent "Scene.java" 2040]
  [javafx.scene.Scene$ScenePeerListener keyEvent "Scene.java" 2501]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification run "GlassViewEventHandler.java" 216]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification run "GlassViewEventHandler.java" 148]
  [java.security.AccessController doPrivileged "AccessController.java" -2]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler lambda$handleKeyEvent$353 "GlassViewEventHandler.java" 247]
  [com.sun.javafx.tk.quantum.QuantumToolkit runWithoutRenderLock "QuantumToolkit.java" 389]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler handleKeyEvent "GlassViewEventHandler.java" 246]
  [com.sun.glass.ui.View handleKeyEvent "View.java" 546]
  [com.sun.glass.ui.View notifyKey "View.java" 966]
  [com.sun.glass.ui.win.WinApplication _runLoop "WinApplication.java" -2]
  [com.sun.glass.ui.win.WinApplication lambda$null$148 "WinApplication.java" 191]
  [java.lang.Thread run "Thread.java" 745]]}

**Comment by RagnarSvenssonKing** [comment] 2016-11-11 11:03
Thanks for the reports, don't forget to state steps-to-reproduce (even if you are unsure of what you did) so we have some means of investigating. Also use [Help > Report Issue] to get some bonus data about your setup.

**Comment by erikangelin-king** [comment] 2016-12-02 22:29
Can't repro this, has it happened again? We fixed one issue late september that could have caused this but surely you were using a newer version?

**Comment by sofiahe** [comment] 2016-12-05 09:02
This was one of the random crahes I got when fiddling around, i have no idea what caused it. I havent seen any problmes recently when editing  script file.

**Comment by sofiahe** [comment] 2017-01-24 10:56
Close as cant reproduce?

**Comment by erikangelin-king** [comment] 2017-01-24 11:16
Can't reproduce

**Closed by erikangelin-king** 2017-01-24 11:16 UTC
Labels: serious
