### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by amel** [defold/editor2-issues#2873] opened 2019-12-16 16:20 UTC
### Expected behaviour
Open the `main.atlas` file.

### Actual behaviour
Showing this null pointer exception.

### Steps to reproduce
It happened randomly and I can't seem to reproduce.

<hr/>

<table>
<tr><td>Build time</td><td>2019-11-29T13:37:43.182609</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>39b2b2d4bd91ffd166a5776bd998912a0ec9758c</td></tr>
<tr><td>Defold engine sha</td><td>2be2687cbb670c2dbe9cf2e99577bc3338561778</td></tr>
<tr><td>Defold version</td><td>1.2.164</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"2b145cd58e5b4c7fbfc208cc170616f0"'>2b145cd58e5b4c7fbfc208cc170616f0</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 6100</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-14.2.16</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.1</td></tr>
<table>

**Comment by britzl** [comment] 2019-12-17 11:20
Duplicate of #2696

**Closed by britzl** 2019-12-17 11:20 UTC
Labels: editor, more-info, serious
