### ISSUE TITLE
GLException when closing atlas with missing images

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#1852] opened 2018-04-30 06:57 UTC
### Steps to reproduce

1. Open atlas with missing images.
2. Close the atlas file.

<hr/>

<table>
<tr><td>Build time</td><td>2018-04-26T18:01:47.417397</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d2aff4d90ed624f24194024c4ca4bd52f8ec2a94</td></tr>
<tr><td>Defold engine sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold version</td><td>1.2.126</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"da4b48cef3b94eb28919c6e4ae01d2fd"'>da4b48cef3b94eb28919c6e4ae01d2fd</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by sicher** [comment] 2018-04-30 06:59
Dupe of #1841 ?

**Comment by erikangelin-king** [comment] 2018-04-30 07:09
Yes, duplicate of #1841. Mats has a PR pending some tests.

**Comment by erikangelin-king** [comment] 2018-11-15 13:56
@sicher Think this has been fixed, reopen otherwise.

**Closed by erikangelin-king** 2018-11-15 13:56 UTC
Labels: duplicate, new, serious
