### ISSUE TITLE
Drop down values are not scrollable

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#453] opened 2017-02-03 11:51 UTC
### Expected behaviour
If the number of values in a drop down doesn't fit the drop down area it should b scrollable so all values can be accessed

### Actual behaviour
All values are not accessible

### Steps to reproduce
Create a text node
Scroll down in the Properties view until you reach Pivot
Select Pivot and notice that since it's almost at the bottom of the screen all values do not fit. I am for instance unable to reach the value West

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>8e1a317594568cd3ff2fe2cff06eb09661f0475e</td></tr>
<tr><td>Build time</td><td>2017-02-02T15:06:39.724621</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<table>

**Comment by ragnard-king** [comment] 2017-02-09 10:59
Likely a macOS Sierra issue, works as expected on 10.11.6

**Comment by ragnard-king** [comment] 2017-02-10 14:00
Looks like this is a known JavaFX that was fixed in `1.8.0_60`: https://bugs.openjdk.java.net/browse/JDK-8092942

@britzl I see from the report that you are running `1.8.0_45`. Nowadays we bundle `1.8.0_101` which means you are either not using the bundled JRE for some reason, or you have not re-installed Editor2 since we were using `1.8.0_45` as we sadly don't yet update the JRE as part of the updates.

**Comment by ragnard-king** [comment] 2017-02-16 15:30
Closing, confirmed this was due to an old JRE version.

**Closed by ragnard-king** 2017-02-16 15:30 UTC
Labels: blocker
