### ISSUE TITLE
debug start is very long time wait

### ISSUE THREAD

**Issue by jonglae** [defold/editor2-issues#2670] opened 2019-06-27 13:47 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-06-25T16:22:36.249758</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>39e92de4e2d97ab951ae10cfba7302bbaeec0d2f</td></tr>
<tr><td>Defold engine sha</td><td>d7042d5368c338ed5d66b6dff9c60a20924385ac</td></tr>
<tr><td>Defold version</td><td>1.2.157</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"d88107beb20542f0a71ddbb44fd528b7"'>d88107beb20542f0a71ddbb44fd528b7</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 560/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 390.87</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-30deepin-generic</td></tr>
<table>

**Comment by markusgustavssonking** [comment] 2019-07-02 12:50
"MenuButtonSkinBase"
Duplicate of https://github.com/defold/editor2-issues/issues/2572

**Closed by markusgustavssonking** 2019-07-02 12:50 UTC
