### ISSUE TITLE
Keyboard shortcuts for changing tools in collection editor

### ISSUE THREAD

**Issue by dapetcu21** [defold/editor2-issues#1126] opened 2017-08-14 20:21 UTC
Editor 1 had Cmd + 1/2/3

I mean these tools:
<img width="172" alt="screen shot 2017-08-14 at 23 21 33" src="https://user-images.githubusercontent.com/428060/29290024-5445f730-8147-11e7-9b79-6527a575937a.png">

**Comment by erikangelin-king** [comment] 2017-08-15 07:48
Duplicate of #898

**Closed by erikangelin-king** 2017-08-15 07:48 UTC

**Comment by ragnard-king** [comment] 2017-09-20 08:52
Better shortcut support, as well as shortcuts that are more aligned with editor1, is available in the latest update.
