### ISSUE TITLE
Script errors do not show line numbers which makes it super hard to debug

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#330] opened 2016-12-14 09:16 UTC
The Build Errors tab doesn't show any line numbers for script errors and it is not possible to click on an error to go to the file and line either.

**Comment by ragnard-king** [comment] 2016-12-14 12:37
Duplicate of #307

**Comment by ragnard-king** [comment] 2016-12-15 08:16
Fixed.

**Closed by ragnard-king** 2016-12-15 08:16 UTC
