### ISSUE TITLE
[Linux] Updater question dialog is not modal

### ISSUE THREAD

**Issue by mathiaswking** [defold/editor2-issues#61] opened 2016-09-15 15:57 UTC
After the update patch was downloaded, the question about updating ended up behind all other windows on the desktop.

(Also, we can probably increase the time between the update checks. currently 1 minute)

**Comment by ragnard-king** [comment] 2016-10-31 12:52
@mathiaswking I can't reproduce this. Did this happen consistently or only once?

**Comment by ragnard-king** [comment] 2017-03-06 08:27
Fixed by https://github.com/defold/defold/pull/1382

**Closed by ragnard-king** 2017-03-06 08:27 UTC
Labels: serious
