### ISSUE TITLE
java.lang.NullPointerException: unknown

### ISSUE THREAD

**Issue by amel** [defold/editor2-issues#2874] opened 2019-12-16 18:20 UTC
I got this error while switching tabs. I can't reproduce this.

<hr/>

<table>
<tr><td>Build time</td><td>2019-11-29T13:37:43.182609</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>39b2b2d4bd91ffd166a5776bd998912a0ec9758c</td></tr>
<tr><td>Defold engine sha</td><td>2be2687cbb670c2dbe9cf2e99577bc3338561778</td></tr>
<tr><td>Defold version</td><td>1.2.164</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"9bb5e6bc0a88407489208beab69a912a"'>9bb5e6bc0a88407489208beab69a912a</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 6100</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-14.2.16</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.1</td></tr>
<table>

**Comment by amel** [comment] 2019-12-16 18:22
Might be related to #2873

**Comment by amel** [comment] 2019-12-16 18:37
Both are indeed related. This happens when the `Texture` property of a `GUI` component is active and you click on a random tab. 

![18cf66f490584daf583915f40fff0cbb](https://user-images.githubusercontent.com/10830880/70933037-6a7da580-203b-11ea-9804-e1b96ec43789.gif)

**Comment by britzl** [comment] 2019-12-17 11:19
Duplicate of #2696

**Closed by britzl** 2019-12-17 11:19 UTC
