### ISSUE TITLE
Error when running/starting with Debug

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2580] opened 2019-05-01 09:46 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-04-30T13:25:18.384697</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b8b891be5ba3e650202848d8b84ddc2ca2ed513a</td></tr>
<tr><td>Defold engine sha</td><td>11b1e7662dd68172fca551c52cba248eea16a364</td></tr>
<tr><td>Defold version</td><td>1.2.152</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"8c5ef79ac38b4371b4ab4b3fe9e50fd6"'>8c5ef79ac38b4371b4ab4b3fe9e50fd6</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4600</td></tr>
<tr><td>GPU Driver</td><td>4.3.0 - Build 20.19.15.4835</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment] 2019-05-02 09:06
Duplicate of #2374.

**Closed by matgis-king** 2019-05-02 09:06 UTC
Labels: duplicate, serious, unhelpful-error
