### ISSUE TITLE
Error: java.util.concurrent.ExecutionException:

### ISSUE THREAD

**Issue by Qwarr** [defold/editor2-issues#2575] opened 2019-04-30 02:31 UTC
### Expected behaviour
Pretting Build button to build the game.

### Actual behaviour
Getting this error when trying to build.

java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.defold.libs.TexcLibrary
java.lang.NoClassDefFoundError: Could not initialize class com.defold.libs.TexcLibrary

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-04-29T14:42:28.192463</td></tr>
<tr><td>Defold channel</td><td>stable</td></tr>
<tr><td>Defold editor sha</td><td>11b1e7662dd68172fca551c52cba248eea16a364</td></tr>
<tr><td>Defold engine sha</td><td>11b1e7662dd68172fca551c52cba248eea16a364</td></tr>
<tr><td>Defold version</td><td>1.2.152</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"79d9282423934535847c482dbd793284"'>79d9282423934535847c482dbd793284</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 760/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Qwarr** [comment] 2019-04-30 02:36
Closing and reopening the editor did fix the issue. 

Previously though I was making several android builds and went to make a windows build and then the error happened. (didn't make any windows builds prior to the android ones)

**Comment by markusgustavssonking** [comment] 2019-04-30 09:07
I am unable to reproduce this issue. Closing the ticket. Please re-open if it happens again.

**Closed by markusgustavssonking** 2019-04-30 09:07 UTC
Labels: more-info
