### ISSUE TITLE
Ctrl+shift+R does nothing

### ISSUE THREAD

**Issue by linusc-king** [defold/editor2-issues#265] opened 2016-12-07 09:29 UTC
### Expected behaviour
Open resource dialog is shown

### Actual behaviour
Nothing is shown

### Steps to reproduce
Open a project and press ctrl+shift+R

<hr/>
Defold version: 1.2.95
Defold sha: 7ca47a7f7aa0e4809e31ab2274fd1693a1fc5a7e
Platform: Windows 7 6.1 (x86)
Java version: 1.8.0_102-b14

**Comment by ragnard-king** [comment] 2016-12-07 09:33
Hi @linusc,

Thanks for reporting!

Are you able to open the resource dialog using the menu (`File -> Open Asset`)?

**Comment by Malmer** [comment] 2016-12-07 09:38
Cmd+Shift+R works on macos though. Allthough I would prefer a simpler hotkey. Like Cmd+P in sublime.

**Comment by linusc-king** [comment] 2016-12-07 09:47
@ragnard-king You are welcome!

Yes it works fine from the menu.

Upon further testing, several other shortcuts are also not working, ctrl-u, ctrl-b, ctrl+shift+F. It may be possible that no shortcuts are working.

**Comment by ragnard-king** [comment] 2016-12-07 09:49
OK thanks, then this is a duplicate of https://github.com/defold/editor2-issues/issues/151.

**Closed** 2017-01-17 15:29 UTC
Labels: duplicate
