### ISSUE TITLE
Build error doesnt open the file directly when clicked on the error

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#311] opened 2016-12-12 13:06 UTC
1. Create a build error (for instance open a collection and add two game objects with same ID)
2. Build
3. Build error is shown
4. Click on the main collection  file

Actual result:
Nothing happens, would be great if the file in question opened

![screen shot 277](https://cloud.githubusercontent.com/assets/22887289/21100383/1060831c-c074-11e6-8277-06b421dc2647.PNG)

<hr/>
Defold version: 1.2.95
Defold sha: 2fd8732d146f5a252125ce1b210e3793f50e169c
Platform: Windows 7 6.1 (amd64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment] 2016-12-13 09:10
Duplicate of #307

**Closed by RagnarSvenssonKing** 2016-12-13 09:10 UTC
