### ISSUE TITLE
[QRT][Win10 x64 build 14393]: Updating to the current Windows build will make Defold unusable [DEFEDIT-766]

### ISSUE THREAD

**Issue by defold-issues** [defold/editor2-issues#473] opened 2017-02-08 14:11 UTC
**Update**

Initial report was a red herring. Actual issue was bad data in preferences. Deleting defold registry pref entries resolved the issue. Unfortunately we did not export the data before deleting. Logfile provides some insight though:

[editor2.txt](https://github.com/defold/editor2-issues/files/760822/editor2.txt)

~~It can be noticed that if the OS is updated to the current build (rev 14393), and Defold is launched, upon loading any project, the software will remain running in the background, with no option to maximize it, in order to be used.~~

~~Steps to Reproduce:~~

~~1. Make sure to have Defold running on a machine powered by a Windows 10 x64 build earlier than 14393.
2. Update the OS to the current build.
3. Launch Defold and open a project.
4. Notice that the software will remain running in the background with no option to maximize it.~~

~~Note that this issue applies for both x86 and x64 versions of Defold.~~

~~Note that the software will actually be handled as a background process, not as a fully running application. Instead, the Java platform will be the seen by the OS as the running app. Please see the attachments for more details about this issue.~~
<img width="546" alt="dxdiag" src="https://cloud.githubusercontent.com/assets/25633889/22740531/e612b274-ee18-11e6-9982-ee343b025f5b.png">

<img width="501" alt="taskman" src="https://cloud.githubusercontent.com/assets/25633889/22740532/e623302c-ee18-11e6-8aef-47d2e4b12532.png">

[editor2.txt](https://github.com/defold/editor2-issues/files/760822/editor2.txt)

**Comment by sofiahe** [comment] 2017-02-09 07:51
After talking with Ragge we tried to remove the regedit defold folder which solved the problem.

**Comment by sofiahe** [comment] 2017-02-09 07:55
This is already registered as DEFEDIT-766

**Comment by blurymind** [comment] 2017-02-10 08:48
this doesnt affect me on windows 7

**Comment by ragnard-king** [comment] 2017-03-06 08:37
Can't reproduce the actions that lead to bad preferences data, closing.

**Closed by ragnard-king** 2017-03-06 08:37 UTC
