### ISSUE TITLE
NullPointer on rebuild

### ISSUE THREAD

**Issue by karlhenselin** [defold/editor2-issues#2682] opened 2019-07-11 01:58 UTC
### Actual behaviour
NullPointer

### Steps to reproduce
Game was running.
Changed init code in script of game object.
Clicked rebuild in project menu.
However, doesn't happen everytime, so I can't say that this will reproduce it.
<hr/>

<table>
<tr><td>Build time</td><td>2019-06-25T16:22:53.457850</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>39e92de4e2d97ab951ae10cfba7302bbaeec0d2f</td></tr>
<tr><td>Defold engine sha</td><td>d7042d5368c338ed5d66b6dff9c60a20924385ac</td></tr>
<tr><td>Defold version</td><td>1.2.157</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"a2b0e09dc8c44da48f520227156e2f27"'>a2b0e09dc8c44da48f520227156e2f27</a></td></tr>
<tr><td>GPU</td><td>Radeon RX 580 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13543 Compatibility Profile Context 25.20.15002.58</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by markusgustavssonking** [comment] 2019-07-11 06:54
Thanks for the report. Duplicate of  #2572

**Closed by markusgustavssonking** 2019-07-11 06:54 UTC
