### ISSUE TITLE
Unable to "Use theirs" when resolving conflicts

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#145] opened 2016-11-08 10:32 UTC
### Expected behaviour

The remote file replaces the local.

### Actual behaviour

For some files, nothing happens. Exception in log.

### Steps to reproduce

1. Synchronize a project with local, conflicting changes
2. When prompted to resolve conflicts, pick "Use theirs"
3. Nothing happens, exception in log.

```
org.eclipse.jgit.errors.MissingObjectException: Missing unknown 0000000000000000000000000000000000000000
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:145) ~[org.eclipse.jgit-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
	at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:173) ~[org.eclipse.jgit-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
	at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:144) ~[org.eclipse.jgit-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
	at org.eclipse.jgit.lib.Repository.open(Repository.java:287) ~[org.eclipse.jgit-4.2.0.201601211800-r.jar:4.2.0.201601211800-r]
	at editor.git$show_file.invokeStatic(git.clj:96) ~[na:na]
	at editor.git$show_file.invoke(git.clj:81) ~[na:na]
	at editor.git$show_file.invokeStatic(git.clj:83) ~[na:na]
	at editor.git$show_file.invoke(git.clj:81) ~[na:na]
	at editor.sync$get_theirs.invokeStatic(sync.clj:232) ~[na:na]
	at editor.sync$get_theirs.invoke(sync.clj:231) ~[na:na]
	at editor.sync$eval40116$fnk40118_positional__40121.invoke(sync.clj:278) ~[na:na]
	at editor.sync$eval40116$fnk40118__40140$fn__40141.invoke(sync.clj:274) ~[na:na]
	at editor.sync$eval40116$fnk40118__40140.invoke(sync.clj:274) ~[na:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.8.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.8.0.jar:na]
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29) ~[clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.8.0.jar:na]
	at editor.handler$invoke_fnk.invokeStatic(handler.clj:45) [na:na]
	at editor.handler$invoke_fnk.invoke(handler.clj:42) [na:na]
	at editor.handler$run.invokeStatic(handler.clj:66) [na:na]
	at editor.handler$run.invoke(handler.clj:65) [na:na]
	at editor.ui$make_menu_command$fn__21736.invoke(ui.clj:664) [na:na]
	at editor.ui$make_menu_command$reify__21738.handle(ui.clj:678) [na:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462) [jfxrt.jar:na]
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405) [jfxrt.jar:na]
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757) ~[jfxrt.jar:na]
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485) ~[jfxrt.jar:na]
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762) ~[jfxrt.jar:na]
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_112]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:417) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416) ~[jfxrt.jar:na]
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555) ~[jfxrt.jar:na]
	at com.sun.glass.ui.View.notifyMouse(View.java:937) ~[jfxrt.jar:na]
	at com.sun.glass.ui.mac.MacApplication._enterNestedEventLoopImpl(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.mac.MacApplication._enterNestedEventLoop(MacApplication.java:109) ~[jfxrt.jar:na]
	at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:511) ~[jfxrt.jar:na]
	at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:583) ~[jfxrt.jar:na]
	at javafx.stage.Stage.showAndWait(Stage.java:474) ~[jfxrt.jar:na]
	at editor.ui$show_and_wait_throwing_BANG_$fn__20963.invoke(ui.clj:285) ~[na:na]
	at editor.ui$show_and_wait_throwing_BANG_.invokeStatic(ui.clj:284) ~[na:na]
	at editor.ui$show_and_wait_throwing_BANG_.invoke(ui.clj:271) ~[na:na]
	at editor.sync$open_sync_dialog.invokeStatic(sync.clj:425) ~[na:na]
	at editor.sync$open_sync_dialog.invoke(sync.clj:298) ~[na:na]
	at editor.changes_view$eval40492$fnk40494_positional__40496.invoke(changes_view.clj:90) ~[na:na]
	at editor.changes_view$eval40492$fnk40494__40507$fn__40508.invoke(changes_view.clj:84) ~[na:na]
	at editor.changes_view$eval40492$fnk40494__40507.invoke(changes_view.clj:84) ~[na:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.8.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.8.0.jar:na]
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29) ~[clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.8.0.jar:na]
	at editor.handler$invoke_fnk.invokeStatic(handler.clj:45) [na:na]
	at editor.handler$invoke_fnk.invoke(handler.clj:42) [na:na]
	at editor.handler$run.invokeStatic(handler.clj:66) [na:na]
	at editor.handler$run.invoke(handler.clj:65) [na:na]
	at editor.ui$make_menu_command$fn__21736.invoke(ui.clj:664) [na:na]
	at editor.ui$make_menu_command$reify__21738.handle(ui.clj:678) [na:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462) [jfxrt.jar:na]
	at com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$20(GlobalMenuAdapter.java:153) ~[jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462) [jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(GlassSystemMenu.java:238) ~[jfxrt.jar:na]
```

<hr/>

Defold version: dev
Defold sha: 
Platform: Mac OS X 10.11.6 (x86_64)
Java version: 1.8.0_112-b16

**Comment by matgis-king** [comment] 2017-01-05 10:33
This is a duplicate of #373 which has more info about the cause. Closing.

**Closed by matgis-king** 2017-01-05 10:33 UTC
Labels: serious
