### ISSUE TITLE
 editor fails to start  when opening project- log file included

### ISSUE THREAD

**Issue by blurymind** [defold/editor2-issues#466] opened 2017-02-07 23:03 UTC
The editor stopped working. When I open any of the example projects that worked in the previous alpha version, the editor simply crashes without any error pop up. The process just dies before loading the project.

This bug is present in:
version = 1.2.96
sha1 = a48d5f28357da97535eb74640370c9e50598eda0
time = 2017-02-07T18:10:15.172777

I am attaching the log file
[editor2.zip](https://github.com/defold/editor2-issues/files/759282/editor2.zip)

**Comment by blurymind** [comment] 2017-02-07 23:16
After actually reading the log file carefully and also checking the disk space on disk C:
I have concluded that the likely reason for the problem is that disk C runs out of space.

It looks like the editor is dumping a huge cache of temp files every time when opening a project and that doesnt get cleaned up when quiting it or on the next start (about 250 mb). As a result, it eventually depletes my free space on disk c and then fails to load projects altogether - until deleting these folders
![editor-defold2](https://cloud.githubusercontent.com/assets/6495061/22715869/eea4165a-ed8a-11e6-91d1-d8a6a1501a4a.JPG)

Btw I am running the editor from a usb flash thumb

Strangely enough, the previous version of the alpha editor did not have that issue

**Comment by blurymind** [comment] 2017-02-07 23:25
Apologies, this is not a regression, both alpha versions do the same thing. They copy a lot of files to a temporary folder in C drive every single time a project is opened.
My guess is that the entire editor makes a copy of itself there, but it does not clean up that copy when you close it

It would be nice if we had some sort of an error mesage pop up with a warning that the user is out of space on C drive if that happens at least - if it's intended design

**Comment by blurymind** [comment] 2017-02-07 23:31
the files in the temp folder seem to be game compilers for all target devices, not the actual editor.
Interesting :)

**Comment by ragnard-king** [comment] 2017-02-08 08:00
Hi,

- Editor crashing on startup: Sorry about this, we introduced a bad regression yesterday that caused this. It has since been fixed. If you open the editor and leave it at the welcome screen, you should eventually be asked to update to a new version that should work.
- Tempfiles: Yes, this a bad behaviour that we should address. I've created https://github.com/defold/editor2-issues/issues/469 to track this separately.

**Comment by ragnard-king** [comment] 2017-02-08 08:34
Please let us know if you are able to start as usual after receiving an update, so we can close this issue. Thanks!

**Comment by blurymind** [comment] 2017-02-08 10:10
I will update the software when I get back home and report :)
The network at my job is blocking the updater

**Comment by blurymind** [comment] 2017-02-10 00:41
@ragnard-king  I tested this on tonight's version of defold.

The problem still persists. Defold creates a new temporary folder every time I start it, without clearing any of the temporary folders from previous sessions. As a result, with every opening of the editor I eventually deplete the free space on disk C and defold fails to load any projects until I manually go and delete those cache folders it left.

A simple solution to this would be to run a cleantemp() function that removes all the temporary folders from previous sessions before creating one for the current session:

rm -r $userTempFolderPath/defold-unpack*
createTempFolder()

sorry above is probably a crappy example of pseudo code, just trying to illustrate what I mean xD

**Comment by ragnard-king** [comment] 2017-02-10 08:21
Thanks for the update! I think I communicated a bit poorly: What I meant was that the we had a recent regression causing crashes when opening projects (unrelated to disk space). This has since been fixed. We have not yet addressed the temporary files issue, but we will get there :-)

**Comment by blurymind** [comment] 2017-02-10 08:47
Thank you @ragnard-king 
Defold has no issue loading projects for me when there is enough disk space. If that start occurring I will report it asap

**Comment by ragnard-king** [comment] 2017-03-02 08:20
@blurymind We've now improved how we unpack files and we should no longer waste space using temporary files/directories. This change will unfortunately require you to download a new version of the editor from the dashboard as it's not covered by the auto-update process.

**Closed** 2017-05-17 13:23 UTC
Labels: serious
