### ISSUE TITLE
Weird behavior between duplicate copies of models - self teleporting around with no behavior for that coded in

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#822] opened 2017-05-13 07:07 UTC
The weirdness happens in both the editor and the engine

I copy and paste a few copies of a GO with a model on it, move it around, and weird things happen.

![models_close_together](https://cloud.githubusercontent.com/assets/409170/26023435/10a64d8e-3770-11e7-8b76-2ee2eed6ef80.gif)

I leave the objects statically in the world, rotate a camera around, and the objects move on their own.

![duplicates teleporting](https://cloud.githubusercontent.com/assets/409170/26023437/16624444-3770-11e7-9872-334a80fb2f13.gif)

**Comment by subsoap** [comment] 2017-05-14 06:57
To add, they still do it if they have different materials.

**Comment by RagnarSvenssonKing** [comment] 2017-05-31 08:23
Do you mind checking if this is still an issue? I could not reproduce this but it was after a serious of different bug fixes of the model handling, a few which were related to batched rendering.

**Comment by RagnarSvenssonKing** [comment] 2017-06-09 11:45
I will close this assuming it was fixed. Please let us know if the issue remains.

**Closed by RagnarSvenssonKing** 2017-06-09 11:45 UTC
Labels: blocker
