### ISSUE TITLE
[Windows] Build & Launch does not work [DEFEDIT-730]

### ISSUE THREAD

**Issue by jakob-pogulis-king** [defold/editor2-issues#58] opened 2016-09-15 12:47 UTC
It does not work to build on Windows.

An attempt to build results in `dmengine.exe` and `dmengine_release.exe` being dropped to a temporary directory under `C:/Users/jakob.pogulis/AppData/Local/Temp/<numbers>`, but nothing else is placed in the directory.

When attempting to start either `dmengine.exe` or `dmengine_release.exe` from that directory an error occurs saying _"The program can't start because OpenAL32.dll is missing from your computer. Try reinstalling the program to fix this problem."_

There is no alert displayed or any errors visible in logs or the Command window.

---
## **The below information is not about the main problem**

Something that should be unrelated but worth mentioning is that at first Windows Defender put both `dmengine.exe` and `dmengine_release.exe` in quarantine as they were identified as _"Trojan:Win32/Repjexi"_. This seems to be a false positive for a lot of other tools as well (aapt, IntelliJ, etc), and it's the "dropper" part of the editor that is detected. When this occurred the following error message was later displayed in the editor as an alert.

```
{:cause
 "CreateProcess error=2, The system cannot find the file specified",
 :via
 [{:type java.security.PrivilegedActionException,
   :message nil,
   :at
   [java.security.AccessController doPrivileged "AccessController.java" -2]}
  {:type java.io.IOException,
   :message
   "Cannot run program \"C:\\Users\\JAKOB~1.POG\\AppData\\Local\\Temp\\3799395257696885959/dmengine.exe\" (in directory \"C:\\Users\\jakob.pogulis\\Platformer\"): CreateProcess error=2, The system cannot find the file specified",
   :at [java.lang.ProcessBuilder start "ProcessBuilder.java" 1048]}
  {:type java.io.IOException,
   :message
   "CreateProcess error=2, The system cannot find the file specified",
   :at [java.lang.ProcessImpl create "ProcessImpl.java" -2]}],
 :trace
 [[java.lang.ProcessImpl create "ProcessImpl.java" -2]
  [java.lang.ProcessImpl <init> "ProcessImpl.java" 386]
  [java.lang.ProcessImpl start "ProcessImpl.java" 137]
  [java.lang.ProcessBuilder start "ProcessBuilder.java" 1029]
  [editor.defold_project$launch_engine invokeStatic "defold_project.clj" 349]
  [editor.defold_project$fn__17066$fnk17061_positional__17067 invoke "defold_project.clj" 602]
  [editor.defold_project$fn__17066$fnk17061__17081$fn__17082 invoke "defold_project.clj" 597]
  [editor.defold_project$fn__17066$fnk17061__17081 invoke "defold_project.clj" 597]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 29]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [editor.handler$invoke_fnk invokeStatic "handler.clj" 25]
  [editor.handler$run invokeStatic "handler.clj" 40]
  [editor.ui$make_menu_command$reify__9621 handle "ui.clj" 640]
  [com.sun.javafx.event.CompositeEventHandler dispatchBubblingEvent "CompositeEventHandler.java" 86]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 238]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 191]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 58]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.EventUtil fireEventImpl "EventUtil.java" 74]
  [com.sun.javafx.event.EventUtil fireEvent "EventUtil.java" 49]
  [javafx.event.Event fireEvent "Event.java" 198]
  [javafx.scene.control.MenuItem fire "MenuItem.java" 462]
  [com.sun.javafx.scene.control.ControlAcceleratorSupport lambda$doAcceleratorInstall$12 "ControlAcceleratorSupport.java" 165]
  [com.sun.javafx.scene.KeyboardShortcutsHandler processAccelerators "KeyboardShortcutsHandler.java" 347]
  [com.sun.javafx.scene.KeyboardShortcutsHandler dispatchBubblingEvent "KeyboardShortcutsHandler.java" 163]
  [com.sun.javafx.event.CompositeEventDispatcher dispatchBubblingEvent "CompositeEventDispatcher.java" 59]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 58]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.EventUtil fireEventImpl "EventUtil.java" 74]
  [com.sun.javafx.event.EventUtil fireEvent "EventUtil.java" 54]
  [javafx.event.Event fireEvent "Event.java" 198]
  [javafx.scene.Scene$KeyHandler process "Scene.java" 3964]
  [javafx.scene.Scene$KeyHandler access$1800 "Scene.java" 3910]
  [javafx.scene.Scene impl_processKeyEvent "Scene.java" 2040]
  [javafx.scene.Scene$ScenePeerListener keyEvent "Scene.java" 2501]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification run "GlassViewEventHandler.java" 216]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification run "GlassViewEventHandler.java" 148]
  [java.security.AccessController doPrivileged "AccessController.java" -2]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler lambda$handleKeyEvent$353 "GlassViewEventHandler.java" 247]
  [com.sun.javafx.tk.quantum.QuantumToolkit runWithoutRenderLock "QuantumToolkit.java" 389]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler handleKeyEvent "GlassViewEventHandler.java" 246]
  [com.sun.glass.ui.View handleKeyEvent "View.java" 546]
  [com.sun.glass.ui.View notifyKey "View.java" 966]
  [com.sun.glass.ui.win.WinApplication _runLoop "WinApplication.java" -2]
  [com.sun.glass.ui.win.WinApplication lambda$null$148 "WinApplication.java" 191]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by RagnarSvenssonKing** [comment] 2016-09-25 21:16
We should contact Microsoft in order to solve the Windows Defender issue: https://www.microsoft.com/en-us/security/portal/developer/ContactUS.aspx

**Comment by ragnard-king** [comment] 2017-03-06 07:56
With latest windows defender definitions I can't reproduce the trojan issue. Closing.

**Closed by ragnard-king** 2017-03-06 07:56 UTC
Labels: serious
