### ISSUE TITLE
Case sensitive file extensions?

### ISSUE THREAD

**Issue by Marurumarsu** [defold/editor2-issues#1092] opened 2017-08-02 21:44 UTC
### Expected behaviour
For the file extensions not to be case sensitive?
### Actual behaviour
The file extensions are case sensitive, apparently.
### Steps to reproduce
At least for .ttf files if the file extension is in caps (.TTF) the Editor didn't recognize it.
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.110</td></tr>
<tr><td>Defold sha</td><td>74358fd428841eb5989659c3e2a8b612e11bf2bb</td></tr>
<tr><td>Build time</td><td>2017-08-02T17:10:09.315291</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1080 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 384.94</td></tr>
<table>

**Comment by matgis-king** [comment] 2017-08-03 07:59
Not sure if we want to change this behavior since this is only really true on Windows. You could potentially run into issues opening your project on another OS. Closing as "by design" for now.

**Closed by matgis-king** 2017-08-03 07:59 UTC
Labels: feature, minor
