### ISSUE TITLE
something caused a null error

### ISSUE THREAD

**Issue by alexm622** [defold/editor2-issues#2641] opened 2019-06-11 15:38 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-06-10T16:32:04.999861</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>f69f5f97a4d3764f2116f2acb00a7d96d5935120</td></tr>
<tr><td>Defold engine sha</td><td>67b68f1e1ac26a3385fb511cdce520fe52387bb0</td></tr>
<tr><td>Defold version</td><td>1.2.156</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"a068555ca8b14bbe813aa0e9bf603e84"'>a068555ca8b14bbe813aa0e9bf603e84</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1050 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 430.64</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by markusgustavssonking** [comment] 2019-06-12 11:33
`javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7.class java.lang.NullPointerException: null
    at javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7(MenuButtonSkinBase.java:188)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)`

Duplicate of #2572

**Closed by markusgustavssonking** 2019-06-12 11:33 UTC
