### ISSUE TITLE
Freeze during build

### ISSUE THREAD

**Issue by olovn** [defold/editor2-issues#1014] opened 2017-06-19 09:57 UTC
Today I've had problems with building the Pet Puzzle project. Editor 2 frequently freezes with high CPU usage while building. This happened in the newest versions of the editor but surprisingly also now when I tried to revert to an older version of the editor.

After a while the build process stopped with a message
"An error occurred: java.lang.OutOfMemoryError: GC overhead limit exceeded"

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>8ca9dddb5a241f77250d483dae977ab62567b84d</td></tr>
<tr><td>Build time</td><td>2017-05-16T17:51:11.582754</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.10.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=094402d5f22a4747ac172e5f42b11e03'>094402d5f22a4747ac172e5f42b11e03</a></td></tr>
<table>

**Comment by matgis-king** [comment] 2017-06-21 14:27
I was unable to reproduce this, so I have asked for more info over email.

**Comment by matgis-king** [comment] 2017-06-22 13:26
Doing a clean reinstall of the editor seems to have solved the issue. Closing for now!

**Closed by matgis-king** 2017-06-22 13:26 UTC
Labels: blocker, more-info
