### ISSUE TITLE
Something wrong with constant-type-worldview?

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1323] opened 2017-10-18 08:56 UTC
I'm setting up a spherical environment map shader which uses constant-type-worldview but stationary models appear to have their texture rotated at certain view orientations.

See here https://gfycat.com/gifs/detail/SeveralBothBarnswallow

This version of this project has the problem example https://github.com/subsoap/defmaterial/tree/ce645a5e06d004be32d7adb0a2f876135f0dd612

**Comment by subsoap** [comment] 2017-10-18 13:27
It looks like it has something to do with when multiple models with the same material setup are in the same scene and using these values. Maybe Sven can help.

**Comment by matgis-king** [comment] 2017-10-19 08:25
@andsveking Any ideas?

**Comment by andsveking** [comment] 2018-08-24 09:47
@subsoap Is this still an issue? I tried the version you linked in the latest Ed2 and couldn't reproduce the issue. 🙁

**Comment by subsoap** [comment] 2018-08-24 09:53
@andsveking I tested that version of the project and don't see the same kind of effect while rotating around so must have been fixed at some point!

**Comment by andsveking** [comment] 2018-08-24 09:58
Good, thanks! Closing this issue for now, let us know if you happen to experience it again.

**Closed by andsveking** 2018-08-24 09:58 UTC
Labels: 3D, engine, serious
