### ISSUE TITLE
"FATAL:ENGINE: Unable to load project file" with Android when building

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#895] opened 2017-05-22 09:21 UTC
[Running on target 'Yifang-NX16A8116K' (192.168.0.102)]
INFO:ENGINE: Defold Engine 1.2.105 (719697b)
FATAL:ENGINE: Unable to load project file: 'http://192.168.0.117:63949/build/game.projectc'
INFO:DLIB: SSDP: Done on address 192.168.0.102

![2017-05-22 01_44_34-](https://cloud.githubusercontent.com/assets/409170/26301172/334e478e-3e95-11e7-9524-ebaf9b890471.png)

Pressing build crashed the app. Tested with debug version of APK. IP is right. I tested messing with firewall rules some but it didn't help. Clearly there is communication though.

Might be https://github.com/defold/editor2-issues/issues/609 again.

**Comment by subsoap** [comment] 2017-05-23 07:49
This happens too on Windows 10 editor for me when building Windows apps too with a copy of the engine running. Have to close the engine each time.

```
[Running on target 'Local' (169.254.153.218)]
INFO:ENGINE: Defold Engine 1.2.105 (719697b)
FATAL:ENGINE: Unable to load project file: 'http://169.254.153.218:62456/build/game.projectc'
INFO:DLIB: SSDP: Done on address 169.254.19.187
INFO:DLIB: SSDP: Done on address 169.254.153.218
INFO:DLIB: SSDP: Done on address 192.168.0.117
```

**Comment by kitstainedheart** [comment] 2017-07-08 14:47
@RagnarSvenssonKing 
Hello, it has been over a month this issue has been added...any update on this?
I have the same issue over here, but apparently it only happens on WINDOWS builds, tested on 7 x64 and 10 x64, both fail to deploy the application, i have tested this since version 100 (currently on 107)...
It happens on both the editor 1 and editor 2
Linux Builds are working fine though...(Debian x64 and Ubuntu x64)
(I suppose Mac is too, since that's what you guys use right?)
(Tested on the vanilla empty project)
Is there any workaround for windows?

**Comment by RagnarSvenssonKing** [comment] 2017-07-10 08:14
Hey! Sorry about the lack of updates regarding this, we will investigate. Thanks for all the info!

**Comment by mathiaswking** [comment] 2017-07-10 16:05
Hi!
We've found an issue in Editor 2 that we should be able to fix tomorrow.

However, I could not reproduce the issue in Editor 1. If editor 1 is not a work around for you, I'd like to have a little more info to go on. For instance, is it exactly the same error message and project setup?

**Comment by RagnarSvenssonKing** [comment] 2017-07-11 12:38
I just pushed a fix so there should be an updated version available in roughly 30 minutes. Thanks for poking us on this issue, really sorry that we didn't respond to this earlier.

**Closed by RagnarSvenssonKing** 2017-07-11 12:38 UTC
Labels: blocker
