### ISSUE TITLE
Tilesource editor has no animation preview or highlighting

### ISSUE THREAD

**Issue by EmilEnglund** [defold/editor2-issues#1106] opened 2017-08-11 07:33 UTC
The new tilesource editor doesn't highlight the selected animation in the viewport and there's no way that I could see, to preview your animation.

These features that exist in the old editor are immensely helpful for understanding which animation you are actually editing and for tweaking animations.

**Comment by ragnard-king** [comment] 2017-08-11 07:40
Hi @EmilEnglund,

1. Your right in that we don't highlight the selected animation, marking this issue as feature to track this.
2. Previewing is supported, select the animation you want to see and use `Scene -> Play` and `Scene -> Stop` to start/stop the playback. This is something we need to document better. A new feature compared to editor1 is that you can also preview animations in-place in where they are actually used, for example on a sprite. Select the sprite component and use `Scene -> Play`.

**Comment by EmilEnglund** [comment] 2017-08-11 08:01
Thanks for the fast reply!

Oh, I see. Previewing on the sprite is definitely useful. However, I don't know how much I would use it since I have to actually change my default animation on my sprite to preview it. It's just a convenience thing but I'm lazy like that.

A few issues with the animation preview in question:

1. I would still very much want to have the preview action on Space since it's both more easy to use and more intuitive than Ctrl+P, Ctrl+T. Space doesn't seem to do anything useful in the scene graph as it is now, if I'm not mistaken.

2. The animation preview in the tilesource editor seems to always use default filtering for sprites, making my pixel art blurred. I'd like it to use nearest, at least if that's my setting in the game project.

3. The animation preview always loops, regardless of my setting in the animation.

**Comment by ragnard-king** [comment] 2017-08-11 08:16
Thanks for the feedback!

1. Absolutely agree with this. The current state is just due to technical limitations that prevent us from having single-key shortcuts (space, F, etc) amongst other things. We need and plan to workaround this. See https://github.com/defold/editor2-issues/issues/898 to track that issue.
2. Bug, good find. Created https://github.com/defold/editor2-issues/issues/1107 to track separately.
3. This is by design, but of course open for discussion. As you've discovered, the current approach to showing and playing animations is quite limited and something we plan on improving, probably worth revisiting playback looping then.

**Comment by ragnard-king** [comment] 2017-09-20 08:57
Space now toggles playback, as well as show/hide palette in tile map editor, so closing this as I think that issue has now been solved and we track #1107 separately. Feel free to re-open otherwise.

**Closed by ragnard-king** 2017-09-20 08:57 UTC
Labels: feature
