### ISSUE TITLE
Opened a project, got null point 

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2624] opened 2019-05-29 21:52 UTC
Did nothing, just opened a project and got the error. 

<hr/>

<table>
<tr><td>Build time</td><td>2019-05-29T10:58:01.987172</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>007189505aa57030bd5cbd89962ed8d163de0e28</td></tr>
<tr><td>Defold engine sha</td><td>838cecd7a26c932e6be73421d98e51ba12f1d462</td></tr>
<tr><td>Defold version</td><td>1.2.155</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"97a9f40753fb4ff6b8afbe89530d8766"'>97a9f40753fb4ff6b8afbe89530d8766</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 430.39</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by vlaaad** [comment] 2019-05-31 07:44
Duplicate of #2572, bug is in our dependency (JavaFX), please watch linked issue

**Closed by vlaaad** 2019-05-31 07:44 UTC
Labels: duplicate, jdk
