### ISSUE TITLE
User can choose the opened gui like a template into itself

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#733] opened 2017-04-26 10:48 UTC
### Expected behaviour
User can't choose opened gui like template into themselves (point 3 in Steps to reproduce)

### Actual behaviour
User can choose the 1.gui like a gui file for template

### Steps to reproduce
1. create 1.gui 
2. Make in 1.gui an template
3. User can choose the 1.gui like a gui file for template
4.  Choose (wrong click in my case) 1.gui like a template 
5. editor2 crashed
<hr/>

![2017-04-26_13-42-15](https://cloud.githubusercontent.com/assets/2209596/25430739/78c3a32c-2a86-11e7-8607-32198b2cd4c4.png)

**Comment by AGulev** [comment] 2017-04-27 15:43
I found the same issue
https://github.com/defold/editor2-issues/issues/140

**Comment by erikangelin-king** [comment] 2017-04-28 11:52
Thanks for the excellent report, closing this as duplicate of the other issue.

**Closed by erikangelin-king** 2017-04-28 11:52 UTC
Labels: duplicate, serious
