### ISSUE TITLE
Not see label text on gui button

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#478] opened 2017-02-11 17:33 UTC
### Expected behaviour
See text on gui button (after stat project all ok)
### Actual behaviour
Not see
### Steps to reproduce
1. Create gui
2. Add button and text components
3. Locate label on button - text not see. (May be I make some wrong, but after start project text show normally)

Screenshot:
http://clip2net.com/s/3HpF4nI
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.97</td></tr>
<tr><td>Defold sha</td><td>6724f8ac845b14b7a54a1305fbf93a34789f674b</td></tr>
<tr><td>Build time</td><td>2017-02-10T17:47:50.773801</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment] 2017-07-13 07:54
Closed as unable to reproduce.

**Closed by RagnarSvenssonKing** 2017-07-13 07:54 UTC
