### ISSUE TITLE
Java NullPointer Exception

### ISSUE THREAD

**Issue by Joakker** [defold/editor2-issues#2766] opened 2019-09-30 01:04 UTC
### Expected behaviour
Normal
### Actual behaviour
Normal
### Steps to reproduce
None, appears at random
<hr/>

<table>
<tr><td>Build time</td><td>2019-09-24T14:21:00.743419</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7c1a314b318aa7ea6de887b6a314c03c7b161464</td></tr>
<tr><td>Defold engine sha</td><td>e07f3bb9e8c970eceda8dce8efd5905fd67fa720</td></tr>
<tr><td>Defold version</td><td>1.2.162</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"53788e5d528a4bf6bcbf1480e8365929"'>53788e5d528a4bf6bcbf1480e8365929</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 20.19.15.5070</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment] 2019-09-30 08:10
Duplicate of #2692, #2696 with no additional info.

**Closed by matgis-king** 2019-09-30 08:10 UTC
Labels: duplicate, jdk, serious
