### ISSUE TITLE
Java error upon deleting open file

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#348] opened 2016-12-16 13:03 UTC
Not sure exactly how I got this and what caused it, but basically what I did was this:

Anim.script was open in a tab (not focused)
I had a collection with some go:s where one of them was referencing anim.script
I deleted the go:s from the collection
Then I deleted anim.script
Got crash. (java.lang.NullPointerException: Unknown)

At no point during this did I save.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>f6271550bf9fdbe0bd959dce1af41dcbbf908ffb</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.2</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=988095d474244d11b0866ffb233e174d'>988095d474244d11b0866ffb233e174d</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment] 2017-07-13 08:01
Closed as unable to reproduce.

**Closed by RagnarSvenssonKing** 2017-07-13 08:01 UTC
Labels: serious
