### ISSUE TITLE
HTML5 build is using middle click for button 2 instead of supporting right click [DEF-2062 DEF-1858 DEF-1634]

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#933] opened 2017-05-24 22:53 UTC
HTML5 build should add support for handling right click on the canvas properly, and not use middle click for button 2, instead it should be button 3.

**Comment by AGulev** [comment] 2018-01-08 17:50
@subsoap fixed in 1.2.113 (can you recheck?)
https://forum.defold.com/t/defold-1-2-113-has-been-released/11641

**Comment by subsoap** [comment] 2018-01-08 19:36
@AGulev This right click menu appears with current build/setup of the HTML5 template.

![rcm](https://user-images.githubusercontent.com/409170/34688772-188e8d9e-f468-11e7-9ea9-80ae3374a314.png)

I think I may have made a modified HTML5 html template which made right click work. I can't remember now, will have to take a closer look later.

**Comment by AGulev** [comment] 2019-01-21 18:54
Solved in 1.2.145
https://forum.defold.com/t/right-click-html5-def-1858-solved/1852/2

DEF-1634 - can't reproduce

**Closed by AGulev** 2019-01-21 18:54 UTC
Labels: engine, serious
