### ISSUE TITLE
Resizing Editor Panel Prioritizing

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1144] opened 2017-08-20 21:04 UTC
When resizing the whole Defold editor the left most panel (Assets, Changed Files) have priority, that side is the one that gets the biggest size changes. Currently when I am resizing the window I always have to make the left and right side smaller because when I make the editor bigger it is the Asset panel/side that gets the biggest change. 

I would think that making the window bigger should increase the area that you are actively working with the most, not the outliner.

P.S.
I didn't really know what to call this one so feel free to give it a better title/summary

**Comment by subsoap** [comment] 2017-08-20 21:47
https://github.com/defold/editor2-issues/issues/825

**Comment by matgis-king** [comment] 2017-08-21 08:19
Closing as duplicate of #825.

**Closed by matgis-king** 2017-08-21 08:19 UTC
Labels: duplicate, serious
