### ISSUE TITLE
go.property name does not accept some special characters

### ISSUE THREAD

**Issue by needsnaming** [defold/editor2-issues#1068] opened 2017-07-13 06:08 UTC
### Expected behaviour
all string values for property names should be displayed as typed in script.

### Actual behaviour
some special characters get removed from the name in the property window.

### Steps to reproduce
add properties with characters:
-_/

not allowing / makes sense, the other 2 I would expect to work.
![capture7](https://user-images.githubusercontent.com/1650079/28152731-3145c708-675f-11e7-932f-1c212d1d8206.PNG)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.109</td></tr>
<tr><td>Defold sha</td><td>fbcf96472ad8cac344677bef6b09bd143057e05f</td></tr>
<tr><td>Build time</td><td>2017-07-12T13:48:24.854824</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 530</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 21.20.16.4542</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment] 2017-07-13 07:06
They are accepted, they are just formatted in a less "programmer" way since they are often meant to be used by non-programmers. Are you saying it is too confusing that the names are formatted differently? The formatted versions in the properties view have no effect, it's just for display purposes.

**Comment by needsnaming** [comment] 2017-07-13 07:24
in that instance I was naming some stuff using numbers. negative 1 and positive 1 both show up as the same property name. 

I guess I can understand formatting _ into spaces as it is a delimiter. but - could be used as -/+ which could cause some confusion. If it is intended for - to be formatted to a space because of its use as a delimiter, don't mind me. I just thought they were not behaving properly. 

I can see the ambiguous nature of my report. 
I just assumed the formatting was unintentional.

**Comment by RagnarSvenssonKing** [comment] 2017-07-13 07:50
Ok, I see, closing as "as designed" then. :)

**Closed by RagnarSvenssonKing** 2017-07-13 07:50 UTC
Labels: more-info
