### ISSUE TITLE
Java.lang.AssertionError: Assert failed: The following resources were changed but never loaded before

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#423] opened 2017-01-25 08:16 UTC
1. Create a new empty project
2. Go to https://github.com/britzl/publicexamples/blob/master/README.md
3. Download the full master zip and extract
4. Copy examples, images, modules, gameproject and read me to your new project via windows explorer
5. Save all
6. Sync and push 

Actual result:
ava.lang.AssertionError: Assert failed: The following resources were changed but never loaded before: /examples/assets/platformer.tilesource, /examples/angrybirds/angrybirds.atlas, 

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>f32230d96b986616b742218d7f1a5bce26519b2e</td></tr>
<tr><td>Build time</td><td>2017-01-24T18:27:02.669047</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=e1df3f947b984259bad52687403e393d'>e1df3f947b984259bad52687403e393d</a></td></tr>
<table>

**Comment by ragnard-king** [comment] 2017-01-25 08:57
Possibly caused by https://github.com/defold/editor2-issues/issues/422

**Comment by ragnard-king** [comment] 2017-01-27 13:29
Fix merged and available in latest update.

**Closed by ragnard-king** 2017-01-27 13:29 UTC
Labels: blocker
