### ISSUE TITLE
Adding a collision shape to a game object removes the object from the main editor view

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#271] opened 2016-12-07 11:43 UTC
[Uploading editor2 - Copy.txt…]()
1. have a game object with a spinemodel
2. Add a collision object to the game object in the outline
3. Add a collision shape

Actual result: the game object spinemodel is removed from the main editor view

After restarting the editor it works again. Attached the log as well.

Defold version: 1.2.95
Defold sha: 7ca47a7f7aa0e4809e31ab2274fd1693a1fc5a7e
Platform: Windows 7 6.1 (x86)
Java version: 1.8.0_102-b14
![collision](https://cloud.githubusercontent.com/assets/22887289/20966479/bd3caa96-bc7a-11e6-8f05-a5733a5528ef.gif)

**Comment by ragnard-king** [comment] 2017-01-20 13:04
Re-tested now, couldn't reproduce so closing.

**Closed by ragnard-king** 2017-01-20 13:04 UTC
Labels: serious
