### ISSUE TITLE
github dependancies not available

### ISSUE THREAD

**Issue by adamwestman** [defold/editor2-issues#113] opened 2016-09-26 07:32 UTC
Attempted to use https://github.com/andsve/dirtylarry/archive/master.zip as game.project dependancy. But library doesn't show up in editor.

Up on project load, libraries are fetched along with other resources. 
Once Editor window is open, they are not visible and available for use.

Tried to restart but no change.

**Comment by britzl** [comment] 2016-09-29 07:04
Isn't this a duplicate of #103 ?

**Comment by RagnarSvenssonKing** [comment] 2016-09-29 11:10
Closing as duplicate

**Closed by RagnarSvenssonKing** 2016-09-29 11:10 UTC
Labels: serious
