### ISSUE TITLE
Overloaded positions and rotations in sub collections are lost [EXTREME BLOCKER]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#1393] opened 2017-11-09 12:13 UTC
Setup:

```
Collection A (created via collection factory)
Sub collection B
      gameobject (with position.x overloaded from A to be 100)
           #script (in init prints go.get_position() => (0,0,0)
```

**Comment by Malmer** [comment] 2017-11-09 12:15
Update: The values don't seem to save in the file either

**Comment by sicher** [comment] 2017-11-09 13:32
Duplicate of #126

**Closed by sicher** 2017-11-09 13:32 UTC
