### ISSUE TITLE
Outline icons would improve with color versions

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1411] opened 2017-11-15 23:24 UTC
![icons](https://user-images.githubusercontent.com/409170/32865699-10431c1e-ca19-11e7-83c8-3c50a68c4157.png)

These icons would be easier to read at a glance if they were colorized.

**Comment by AGulev** [comment] 2018-01-08 18:28
@subsoap duplicate of https://github.com/defold/editor2-issues/issues/1069
can be closed.

**Closed** 2018-01-08 19:19 UTC
Labels: feature
