### ISSUE TITLE
Error when deleting dae file while it is open

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#392] opened 2017-01-12 15:21 UTC
<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>e6b3e14db1c069651d410877ca5e07596bcc4edc</td></tr>
<tr><td>Build time</td><td>2017-01-11T10:00:14.875260</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.2</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=a6ad343baf99408992f2d70c72003249'>a6ad343baf99408992f2d70c72003249</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment] 2017-07-13 08:00
Closed as unable to reproduce.

**Closed by RagnarSvenssonKing** 2017-07-13 08:00 UTC
Labels: serious
