### ISSUE TITLE
Not saving

### ISSUE THREAD

**Issue by paolocarrara** [defold/editor2-issues#1005] opened 2017-06-15 18:06 UTC
### Expected behaviour
I expect to have all my project files saved.

### Actual behaviour
None of them are saved.

### Steps to reproduce
Yesterday, I created a basic project to follow the tutorial as I'm new to game development. Everything went fine.

I closed the editor.

Today when I initialized the project and continued the tutorial, my changes did not save. Neither File > Save All or Ctrl + S worked.

All the previous work was there, but no new modifications were possible. Every build started from the modifications done the day before.

<hr/>

Don't know why it says Defold version 1.2.107 as I'm using the Defold Editor 2. 

<table>
<tr><td>Defold version</td><td>1.2.107</td></tr>
<tr><td>Defold sha</td><td>76926d68154d8a3f714826a6656c8a615e0611ac</td></tr>
<tr><td>Build time</td><td>2017-06-14T12:17:49.600812</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.4.0-78-generic</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment] 2017-07-21 15:04
Closed as unable to reproduce. The save functionality has also gone through a drastic change so I believe it's likely that this issue was fixed in the process. Please report if it happens again!

**Closed by RagnarSvenssonKing** 2017-07-21 15:04 UTC
Labels: blocker, more-info
