### ISSUE TITLE
Changing Max Characters in game.project creates float, not int

### ISSUE THREAD

**Issue by Mattibun** [defold/editor2-issues#1037] opened 2017-06-28 20:23 UTC
### Expected behaviour

Changing Max Characters in game.project increases text-render buffer.

### Actual behaviour

Max Characters entry turns into float. Console message returns:

> WARNING:DLIB: Unable to convert '64000.0' to int

followed by

> WARNING:RENDER: Out of text-render buffer

when I try to populate my really big label I'm using to mimic a text window.

### Steps to reproduce

Open game.project and change the Max Characters value to any other number.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>dbf43e44632639feec25a9a41e47dfa31c97109a</td></tr>
<tr><td>Build time</td><td>2017-06-28T16:40:42.652116</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.11.6-3-ARCH</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by matgis-king** [comment] 2017-06-29 09:07
Duplicate of #1021 
Fixed with defold/defold#1669

**Closed by matgis-king** 2017-06-29 09:07 UTC
Labels: duplicate, quick-win?, serious
