### ISSUE TITLE
Defold freeze on window "loading project, indexing..." when try to open project 

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1073] opened 2017-07-20 09:56 UTC
Reproduced only on windows:
![2017-07-20_12-54-37](https://user-images.githubusercontent.com/2209596/28411818-bad51bea-6d4a-11e7-9a47-a31962b18c06.png)

[editor2.2017-07-20 (1).log.zip](https://github.com/defold/editor2-issues/files/1161889/editor2.2017-07-20.1.log.zip)

**Comment by AGulev** [comment] 2017-07-20 10:17
Bug reproduced only if i use windows 10 function "Bash on windows" using ubuntu https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by RagnarSvenssonKing** [comment] 2017-07-20 10:22
I couldn't find anything in the log for this or the previous issue you registered. It would be great if you could answer the following:

* Did it work on the same machine previously?
* Is it running out of memory? (I don't believe this would result in a freeze, but error/crash, but just checking)
* Is it running out of disk space?
* Have you tried the project on another windows machine and this works?

Since in both cases, it results in a freeze a while after the app has been started, it could be related to something else, e.g. automatic updates. Could you try to start the app and load the project after automatic updates has been disabled? You can do that in the config file in the app installation by clearing the updateurl:
updateurl = https://....
change to:
updateurl =
This should cause the log to say:
[JavaFX Application Thread] DEBUG com.defold.editor.Start - automatic updates disabled (defold.update.url='')

Thanks!

**Comment by AGulev** [comment] 2017-07-20 10:25
@RagnarSvenssonKing I think my previous comment could help

I tried to delete unix subsystem (remove checkbox in Control panel) and editor continue works fine. 

But I still think that it's an issue, because it's a great windows function (possibility to use bash on windows machine )

**Comment by RagnarSvenssonKing** [comment] 2017-07-20 10:28
Ok! Could you make a steps-to-reproduce that details how you started the app on bash on windows etc?

**Comment by AGulev** [comment] 2017-07-20 10:42
Let's continue there: https://github.com/defold/editor2-issues/issues/1071
I think this both bugs are parts of one bug (reason)

**Comment by RagnarSvenssonKing** [comment] 2017-07-20 11:44
Closing as duplicate of #1071

**Closed by RagnarSvenssonKing** 2017-07-20 11:44 UTC
Labels: feature
