### ISSUE TITLE
Commits made from the Editor2 are not visible in the Defold dashboard [DEFEDIT-695]

### ISSUE THREAD

**Issue by alexandru-p** [defold/editor2-issues#390] opened 2017-01-12 15:07 UTC
It can be noticed that pushed changes from Editor2 are not visible in the http://dashboard.defold.com/ web page. Pushed changes from the Stable Editor are visible in the Team tab of the project in the Defold dashboard.

Steps to reproduce:
1. Create a new project or open an existing one.
2. Make changes to any files.
3. Save changes.
4. Go to File > Synchronize
5. push the changed files .
6. Go to http://dashboard.defold.com/, open the project you just pushed the changes and go to the team tab.

Notice that the changes are not shown here. 
![image](https://cloud.githubusercontent.com/assets/23701955/21894908/8b92c706-d8e9-11e6-9dad-4cf4211202a5.png)

Repeat the steps with the Stable editor and see that the changes are visible.
![image](https://cloud.githubusercontent.com/assets/23701955/21894918/962a948c-d8e9-11e6-885c-f2bae88336fe.png)

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>e6b3e14db1c069651d410877ca5e07596bcc4edc</td></tr>
<tr><td>Build time</td><td>2017-01-11T10:00:14.875260</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment] 2017-01-20 13:14
Duplicate of https://github.com/defold/editor2-issues/issues/12

**Comment by ragnard-king** [comment] 2017-01-26 18:53
Fix merged, coming in update shortly.

**Closed by ragnard-king** 2017-01-26 18:53 UTC
Labels: blocker
