### ISSUE TITLE
Text nodes need a visual representation of size, currently only show bounding box of current text [DEFEDIT-4105]

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2179] opened 2018-09-10 01:20 UTC
When changing the size of a text node there is no visual indication of a difference in the bounding box - the bounding box only shows the current area the text occupies. But if a text node is picked it will only pick within its actual size and not where the text can overflow.

**Comment by dapetcu21** [comment] 2018-09-24 10:55
Duplicate of #992? But yeah, I'm working with text nodes all day long on Interrogation and I feel your pain.

**Comment by markusgustavssonking** [comment] 2019-06-11 07:05
Fixed.

**Closed by markusgustavssonking** 2019-06-11 07:05 UTC
Labels: feature, quick-win?

**Comment by dapetcu21** [comment] 2019-06-11 07:06
Omg! I love you! ❤️ You have no idea how welcome this change is for us!

**Comment by markusgustavssonking** [comment] 2019-06-11 07:41
Thank you :)
I changed it to show the actual, scaled size of the node instead of the bounds of the text. I hope this helps.
Change also applies to labels.
