### ISSUE TITLE
Exception klicking "Done" after pull

### ISSUE THREAD

**Issue by linuxfranz** [defold/editor2-issues#1194] opened 2017-09-10 19:56 UTC
### Expected behaviour
Changes of project get pulled from repository.
### Actual behaviour
Klicking on "Done" after the "Pull" step leads to exception.
### Steps to reproduce
Do a synchronize with repository. After the pull klick on "Done".
<hr/>

<table>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>Defold version</td><td>1.2.113</td></tr>
<tr><td>Build time</td><td>2017-09-08T14:12:54.646509</td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics 515 (Skylake GT2) </td></tr>
<tr><td>Defold sha</td><td>ead5b04fb115bb4a5d9d781b38d580d0fc4783b0</td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 17.1.6</td></tr>
<tr><td>OS version</td><td>4.12.9-1-default</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=2af21b1153ad4db1a018afd32d1be95b'>2af21b1153ad4db1a018afd32d1be95b</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by linuxfranz** [comment] 2017-09-10 19:57
Exception:

clojure.lang.ExceptionInfo: handler ':synchronize' in context ':global' failed at ':run' with message 'Setter of node 72057594037928205 (editor.collection/ReferencedGOInstanceNode) :path could not be called'
java.lang.Exception: Setter of node 72057594037928205 (editor.collection/ReferencedGOInstanceNode) :path could not be called
java.lang.NullPointerException: Unknown

**Comment by matgis-king** [comment] 2017-09-11 08:31
Note: This does not look like a Sync issue, but rather a known bug being triggered by the changes introduced by the sync. This looks like a duplicate of the #1127 series of issues. I've added this issue to the list of bugs fixed by pending PR defold/defold#1753.

**Comment by matgis-king** [comment] 2017-09-20 09:15
In-place editing fixes were merged, so this should no longer be an issue.

**Closed by matgis-king** 2017-09-20 09:15 UTC
Labels: blocker
