### ISSUE TITLE
Attach debugger not working in 1.2.120

### ISSUE THREAD

**Issue by petereliassonking** [defold/editor2-issues#1666] opened 2018-02-15 09:19 UTC

**Comment by erikangelin-king** [comment] 2018-03-09 14:27
Hi @petereliassonking ! The target selection was broken for a couple of weeks, resulting in various network related errors. We merged a fix about a week ago. Has this happened again since?

**Comment by AGulev** [comment] 2019-01-06 09:49
I can't reproduce this issue in 1.2.144.

**Comment by vlaaad** [comment] 2019-03-19 12:55
We also released a couple of improvements to debugger recently. Feel free to reopen if you still have this problem.

**Closed by vlaaad** 2019-03-19 12:55 UTC
Labels: blocker, kp
