### ISSUE TITLE
Scale for labels does not update in editor

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#706] opened 2017-04-19 02:32 UTC
Adjust the scale of a label directly in the editor and its scale does not change in editor, does change in engine.

**Comment by rgrams** [comment] 2017-04-21 13:46
Duplicate of #581 ?

**Comment by matgis-king** [comment] 2017-04-24 07:41
Yes, this is the same issue. Closing as duplicate.

**Closed by matgis-king** 2017-04-24 07:41 UTC
Labels: quick-win?, serious
