### ISSUE TITLE
Report missing scripts at build time

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#874] opened 2017-05-18 15:05 UTC
### Expected behaviour
Missing scripts are reported, as a warning preferably when building

### Actual behaviour
Nothing happens, unless bundling with bob, then you get an error

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>d85dc7e615a04a574c0d772a914fe61b5c5f2dab</td></tr>
<tr><td>Build time</td><td>2017-05-18T15:29:25.374476</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment] 2017-06-01 09:38
Closing this after discussion with @Malmer as we couldn't reproduce.

**Closed by ragnard-king** 2017-06-01 09:38 UTC
Labels: blocker
