### ISSUE TITLE
Increase width of resource selection window

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1320] opened 2017-10-18 08:06 UTC
I want to be able to resize this window and have its size remembered, add a min / max dimensions so it can't get bugged.
![2017-10-18 01_05_49-select resource](https://user-images.githubusercontent.com/409170/31707274-9ed39272-b3a0-11e7-8e6e-54d83c9071fe.png)

**Comment by Jerakin** [comment] 2017-10-19 07:59
https://github.com/defold/editor2-issues/issues/1185

**Comment by matgis-king** [comment] 2017-10-19 08:19
Closing as Duplicate of #1185.

**Closed by matgis-king** 2017-10-19 08:19 UTC
Labels: duplicate
