### ISSUE TITLE
Collision shape scales with parent in editor but not in engine

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#682] opened 2017-04-13 02:31 UTC
In editor scaling a 32x32 tile with a 32x32 collision shape to match it

![2017-04-12 19_29_27-defold editor 2 0 - 4 platformer basics](https://cloud.githubusercontent.com/assets/409170/24987766/907a0180-1fb6-11e7-9735-aa01c2113bad.png)

![2017-04-12 19_29_39-4 platformer basics](https://cloud.githubusercontent.com/assets/409170/24987760/893c0a6c-1fb6-11e7-80c9-9b4ee04fd22b.png)

In engine running

**Comment by britzl** [comment] 2019-01-17 10:21
Duplicate of: https://github.com/defold/editor2-issues/issues/1380

**Closed by britzl** 2019-01-17 10:21 UTC
Labels: serious
