### ISSUE TITLE
Try delete script from GO recieve error

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#554] opened 2017-03-04 16:51 UTC
### Expected behaviour
Delete script from GO
### Actual behaviour
Receieve error clojure.lang.ExceptionInfo: handler ':delete' in context ':workbench' failed at ':run' with message 'null'
java.lang.NullPointerException: Unknown
### Steps to reproduce
1. Add script to GO
2. Save GO
3. Try delte script from GO
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.99</td></tr>
<tr><td>Defold sha</td><td>e6ae0e46db3afc500108d4337d351f663a97cacd</td></tr>
<tr><td>Build time</td><td>2017-03-03T14:44:13.437928</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment] 2017-03-06 09:12
Hi @tarnumius!

Thanks for the report, however I can't reproduce this. Do you consistently get the error? Are you able to share a small project where you can can reproduce it?

**Comment by tarnumius** [comment] 2017-03-06 09:19
Hi, @ragnard-king 

I try, later.

**Comment by tarnumius** [comment] 2017-03-06 10:28
I cannot reproduce now, may be it was effect about other my issue with access dinied files

**Comment by ragnard-king** [comment] 2017-06-13 11:50
I'll close this issue now because I think it's likely the consequence of another since fixed issue and I haven't seen it occur again. Feel free to re-open if it happens again.

**Closed by ragnard-king** 2017-06-13 11:50 UTC
Labels: more-info
