### ISSUE TITLE
Installing iOS bundle [DEFEDIT-1089]

### ISSUE THREAD

**Issue by DenizTemizer** [defold/editor2-issues#1091] opened 2017-08-01 13:56 UTC
### Actual behaviour
Bundling game with Defold 2 for iOS -> works fine with no errors.
But when I try to install via ios-deploy package:
> [ 70%] VerifyingApplication
2017-08-01 15:34:38.755 ios-deploy[19808:1664724] [ !! ] Error 0xe8000067: There was an internal API error. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

Installing via iTunes doesn't work too, no errors thrown.

### Infos
- It's a local project
- Installing the bundle from Defold 1 works
- Using [defold-timer](https://github.com/britzl/defold-timer) in my project
- Unix executable bundled with Defold 2 has zero bytes

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.110</td></tr>
<tr><td>Defold sha</td><td>80a504baca2e51e7c8ea76cf90d139fe48385186</td></tr>
<tr><td>Build time</td><td>2017-08-01T15:30:50.031643</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>Intel Iris Pro OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.25.13</td></tr>
<table>

**Comment by matgis-king** [comment] 2017-08-02 08:07
Duplicate of #1045?

**Comment by matgis-king** [comment] 2017-08-03 08:51
While I was able to reproduce the issue in the new editor using build `80a504baca2e51e7c8ea76cf90d139fe48385186` from which the error was reported, I could not reproduce this after updating to the latest version of Editor 2. The problem also seems to have gone away for the user from the other report we have for this (#1045).

Are you still able to reproduce the issue after updating Editor 2?

**Comment by DenizTemizer** [comment] 2017-08-07 12:12
Updated to 1.2.111 and the unix executable is still "Zero bytes".
Tested on two systems with different profiles.

Any ways I could provide more information?

**Comment by DenizTemizer** [comment] 2017-08-09 12:16
I guess I found the cause of my problems.
This only happens when I'm working with a local project which isn't backed up into the cloud / dashboard.

How it works:
- Creating a project in the cloud
- Signing iOS application
- Bundling

How it doesn't work:
- Creating a project on local machine
- Signing iOS Application -> gives back Error
- Bundling -> Unix executable with zero bytes

I guess working on local projects isn't successfully implemented yet.
See #1105.

**Comment by matgis-king** [comment] 2017-08-09 15:23
Thanks for digging into this some more! If I understand you correctly the issue only occurs if you choose **Sign iOS App...** from the Project menu?

The **Sign iOS App...** feature is actually intended for use with the Defold Dashboard only. It signs and uploads an iOS executable and posts it to the Dashboard for your project so other members of your team can easily install it on their devices. They can then start it on their device and connect to it from the editor, which enables them to **Hot Reload** changes from the editor on their device without continually having to rebuild and restart the game.

This is a special Developer-only version of the App, though. If you want a bundle you can post on the App Store, you should instead choose **Bundle > iOS Application...** from the Project menu. This creates a standalone `ipk` file containing all the game assets and executable which you should be able to install to your device using iTunes.

Now, we should do a better job of describing what the **Sign iOS App...** feature is for, and give a better error message in case the project is not connected to the Defold Dashboard. But it does not surprise me that **Sign iOS App...** fails if your project is not linked to the Defold Dashboard.

However, **Bundle > iOS Application...** should still work for an unlinked project, so if you're unable to install the resulting `ipk` because your executable is zero bytes, this is a serious bug!

**Comment by DenizTemizer** [comment] 2017-08-10 08:28
**Bundle > iOS Application...** is producing a executable with zero bytes as long as the application isn't hosted in the cloud.
I guessed the problem could be with the **Sign iOS App** process otherwise I don't know why it couldn't work locally?

**Some more information:**
- Cloned project folder from the one which is hosted in the cloud
- Deleted everything inside **my build path** and **.internal > cache**
- Opened this cloned project with Defold 2 and picked **from disk**
- **Bundle > iOS Application...** results in executable with zero bytes

Well somehow it now fails with the cloud hosted version too, gonna have a look into it.
Could logs be useful to track this down?

**Comment by matgis-king** [comment] 2017-08-10 09:03
OK, it sounds like we have a bug that does not happen every time. We'll have to investigate this further.

If you have any logs of a session where the error occurred, we'd love to see them! If you send them to me in a private message on the Defold forum I'll attach the logs to the issue in our internal tracking system. I'm `mats.gisselson` on the Defold forum.

**Comment by matgis-king** [comment] 2017-08-17 15:38
This was a tricky one. We've managed to reproduce the issue but are still working on a fix. A potential workaround if you're stuck would appear to be to install XCode. You have to start XCode and let it modify the system in order to install the bundled Developer Tools. As far as we can tell, that appears to "fix" the issue.

Hopefully we should have a proper fix for this soon.

**Comment by ragnard-king** [comment] 2017-08-18 14:30
We believe this issue has been fixed in the latest update. Please re-open if the problem persists!

**Closed by ragnard-king** 2017-08-18 14:30 UTC
Labels: blocker, more-info

**Comment by DenizTemizer** [comment] 2017-08-22 16:53
Updated the Editor and tested on my project.
Works like a charm, thanks!
