### ISSUE TITLE
Text node containers should show size information visually in some way

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1146] opened 2017-08-23 00:40 UTC
Text nodes show the box outline of the current text, but does not show any visual information of the total size specified in the properties. Would be useful to see, maybe in a secondary color when the node is selected.

![2017-08-22 17_39_10-defold editor 2 0 - defsp](https://user-images.githubusercontent.com/409170/29593706-e5c73e02-8760-11e7-8018-5198b00dbe6f.png)

**Comment by erikangelin-king** [comment] 2017-08-23 07:49
Duplicate of #992, #1129

**Closed by erikangelin-king** 2017-08-23 07:49 UTC
Labels: duplicate
