### ISSUE TITLE
Tab bar is messed up after choosing Close Others

### ISSUE THREAD

**Issue by matgis-king** [defold/editor2-issues#836] opened 2017-05-15 08:31 UTC
![tab-bar-messed-up](https://cloud.githubusercontent.com/assets/22448941/26048935/720191e8-3959-11e7-9892-3e5874da014a.png)

### Steps to reproduce
1. Open enough Assets in the editor to fill the Tab Bar, and then some.
2. Right-click a tab and choose Close Others from the context menu.

### Expected behaviour
Other tabs are closed. The "More Tabs" disclosure triangle menu disappears and the remaining tab is placed at the leftmost point of the tab area.

### Actual behaviour
Other tabs are closed. Sometimes the remaining tab appears in the middle of the tab area, and sometimes it seems to be somewhere offscreen where it cannot be seen. Opening additional tabs places them to the right of the remaining tab, but it appears they are clipped to some invisible region.

<hr/>

<table>
<tr><td>Defold version</td><td>dev</td></tr>
<tr><td>Defold sha</td><td></td></tr>
<tr><td>Build time</td><td></td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by subsoap** [comment] 2017-05-15 08:58
https://github.com/defold/editor2-issues/issues/364

**Comment by ragnard-king** [comment] 2017-05-23 11:13
Closing as duplicate of https://github.com/defold/editor2-issues/issues/364

**Closed by ragnard-king** 2017-05-23 11:13 UTC
Labels: blocker, duplicate
