### ISSUE TITLE
Error showing "_" symbol

### ISSUE THREAD

**Issue by benjaminglaser** [defold/editor2-issues#323] opened 2016-12-13 13:03 UTC
<img width="1429" alt="screen shot 2016-12-13 at 14 01 43" src="https://cloud.githubusercontent.com/assets/1716052/21141329/d4534246-c13c-11e6-8b9b-9bcac44c3684.png">

### Expected behaviour
"game_project"

### Actual behaviour
"game3project"

### Steps to reproduce

<hr/>
Defold version: 1.2.95
Defold sha: 6281048b5c90f95c4ec2973b1b9c8f8e7f3c0b9c
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment] 2017-07-13 08:04
Closed as unable to reproduce. Probably "fixed" by us changing the font.

**Closed by RagnarSvenssonKing** 2017-07-13 08:04 UTC
Labels: more-info
