### ISSUE TITLE
Selection is offset from the cursor position in curve editor

### ISSUE THREAD

**Issue by CandyFace** [defold/editor2-issues#605] opened 2017-03-20 10:03 UTC
Only tested on mac, can't say whether it's an exclusive issue or not.

clicking or selecting in the curve editor yields that the selection is offset from the actual cursor position.

![offset-bug](https://cloud.githubusercontent.com/assets/1045397/24095017/845753d4-0d5b-11e7-97d2-eacb2b53ba52.gif)

## Steps to reproduce:
1. open a particlefx file or anything that enables curve editing
2. click or drag directly on node or select somewhere else.

### expected result
Node gets dragged or is selected or selection starts from the top-left of the cursor.

### actual result
Nothing, you have to click or drag slightly diagonally above the node to select or drag it.

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>1afccdb2cd42ca3bc7612a0496dfa6d434a8ebf9</td></tr>
<tr><td>Build time</td><td>2017-03-17T11:46:16.030571</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by matgis-king** [comment] 2017-06-20 14:47
Duplicate of #673, which was fixed a while back.

**Closed by matgis-king** 2017-06-20 14:47 UTC
Labels: quick-win?, serious
