### ISSUE TITLE
Issues compiling some apps with editor version 1.2.140

### ISSUE THREAD

**Issue by Qwarr** [defold/editor2-issues#2279] opened 2018-10-30 19:46 UTC
### Expected behaviour
Able to compile app.

### Actual behaviour
Trying to compile an app gets to about 50% then throws an error, then continues and infinitely stays at about 99%.

The error: 
java.util.concurrent.ExecutionException: java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to java.lang.Character
java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to java.lang.Character

### Steps to reproduce
I'm not sure how to reproduce other than going back to version 1.2.139 I can continue as normal. 

<hr/>

<table>
<tr><td>Build time</td><td>2018-10-30T10:40:05.060369</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>96dc250f88a9afd4211c5389d7e22e9e01d91943</td></tr>
<tr><td>Defold engine sha</td><td>2fc8ff32c9fa3a16c8f4ce44eba8351c054b33dd</td></tr>
<tr><td>Defold version</td><td>1.2.140</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"9e7718db5c8940afaefaec9da27a7c46"'>9e7718db5c8940afaefaec9da27a7c46</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 760/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment] 2018-10-30 22:02
This looks like a font compilation issue. We just merged a hot fix for it and will have a closer look tomorrow.

**Comment by jhonnyking** [comment] 2018-10-31 14:54
Looks good! Was not able to reproduce any crashes/editor locking post-fix.

**Closed by jhonnyking** 2018-10-31 14:54 UTC
Labels: blocker

**Comment by AukeTembrink** [comment] 2018-11-01 01:11
@jhonnyking this error or at least a really similar one is popping up when opening he html5 debug version of the game with url params.


### Expected behaviour
Read url params
### Actual behaviour
crashes as soon as a url parameter is given
### Steps to reproduce
Read in the url parameter on game.script

`player = html5.run("try{(document.URL.match(/player=([a-z,A-Z])\\w+/)[0]).split('=')[1];}catch(err){}")`

opening the game in html5 debug mode will throw an error in defold.
`java.nio.file.InvalidPathException: Illegal char <?> at index 10: index.html?player=test`
<hr/>

<table>
<tr><td>Build time</td><td>2018-10-30T23:10:56.066860</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ab5b75744568cc7562c025c14c89f4069ad31439</td></tr>
<tr><td>Defold engine sha</td><td>2fc8ff32c9fa3a16c8f4ce44eba8351c054b33dd</td></tr>
<tr><td>Defold version</td><td>1.2.140</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"8e1e7cb2468e42ea96d5b4d3adee652b"'>8e1e7cb2468e42ea96d5b4d3adee652b</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX TITAN X/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 411.70</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>
