### ISSUE TITLE
Was messing around with guis with some copy pasting before adding gui to go. Got error when saving.

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#872] opened 2017-05-18 13:20 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>4543f7e70ccd7ef72603e4049f1ca2097236282f</td></tr>
<tr><td>Build time</td><td>2017-05-18T15:00:28.664218</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=b1ebd7ccf828487eabcbcbd962997258'>b1ebd7ccf828487eabcbcbd962997258</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment] 2017-07-21 14:54
Closed as unable to reproduce

**Closed by RagnarSvenssonKing** 2017-07-21 14:54 UTC
Labels: serious
