### ISSUE TITLE
Save all error

### ISSUE THREAD

**Issue by ThaPro** [defold/editor2-issues#803] opened 2017-05-11 13:29 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>7b2ef0aa2f657205c680ddded145b245e11a8ed7</td></tr>
<tr><td>Build time</td><td>2017-05-10T13:30:34.611101</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=165a095659dc44a4bf79b5dc731174db'>165a095659dc44a4bf79b5dc731174db</a></td></tr>
<table>

**Comment by ragnard-king** [comment] 2017-05-24 08:51
Can't find reported error so we don't have much to go on. Can you consistently reproduce this?

**Comment by ThaPro** [comment] 2017-05-24 16:41
No, had to restart then it worked

**Comment by ragnard-king** [comment] 2017-06-01 10:10
Internal: found the error: https://sentry.io/defold/editor2/issues/271219728/

**Comment by ragnard-king** [comment] 2017-09-07 11:49
Couldn't reproduce or find original error so closing this. Save all has changed substantially (for the better, hopefully) so this could have been fixed by that.

**Closed by ragnard-king** 2017-09-07 11:49 UTC
Labels: blocker, more-info
