### ISSUE TITLE
Spines don't work in HTML5 or on device if they got a default skin set

### ISSUE THREAD

**Issue by ludd1** [defold/editor2-issues#714] opened 2017-04-20 10:04 UTC
### Expected behaviour
Spine animations look the same in html5 as they do when built to local.
### Actual behaviour
Spine animations work when built to local. But are not shown correctly when built to html5 or to a targeted device.
### Steps to reproduce
1. Setup a spinemodel that does not have any skins. 
2. Set the skin property as default in Defold.
3. Build to local, see the animation work
4. Build to html5 and only parts of the animation will show. 

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.102</td></tr>
<tr><td>Defold sha</td><td>bb87ca6754cf3a984f7dd3c9337f9ab24ac14755</td></tr>
<tr><td>Build time</td><td>2017-04-20T10:13:23.763796</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by matgis-king** [comment] 2017-10-16 12:56
Duplicate of #1049, which has more info.

**Closed by matgis-king** 2017-10-16 12:56 UTC
Labels: duplicate
