### ISSUE TITLE
Building not done when game launches [DEFEDIT-1125]

### ISSUE THREAD

**Issue by leXorNet** [defold/editor2-issues#924] opened 2017-05-23 12:56 UTC
### Expected behaviour
Editor should be unlocked/ready to use at exactly the same time the game launches.

### Actual behaviour
Editor says building, stays locked and wont update console for some additional time (~10 seconds) after game is launched.

### Steps to reproduce
Build and run (big?) project.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.105</td></tr>
<tr><td>Defold sha</td><td>0eda508c32d17e8348ddee69f03b110ae5845e6b</td></tr>
<tr><td>Build time</td><td>2017-05-23T13:13:57.948197</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.10.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by subsoap** [comment] 2017-05-23 18:16
Probably it's waiting for the game to initialize and communicate with the editor.

**Comment by leXorNet** [comment] 2017-05-23 20:38
@subsoap Could be. But Editor1 does not have this lag when doing build and run on the very same project.

**Comment by RagnarSvenssonKing** [comment] 2017-05-24 06:57
Blocker since it hurts iteration time really badly.

**Comment by erikangelin-king** [comment] 2017-09-25 07:07
This was likely caused by us looking for external file changes when switching back to the editor from some other application (in this case, the launched game). We recently merged some optimizations that should significantly shorten that time if you have large dependencies. Please reopen if this is still an issue!

**Comment by ragnard-king** [comment] 2017-11-03 08:24
Re-opening this as we discovered another reason this is happening. Working on a fix.

**Comment by ragnard-king** [comment] 2017-11-03 11:16
Fix for is coming in next update.

**Closed by ragnard-king** 2017-11-03 11:16 UTC
Labels: blocker
