### ISSUE TITLE
Opening Britzl Atlas from Git hub examples

### ISSUE THREAD

**Issue by CoCopia** [defold/editor2-issues#393] opened 2017-01-12 19:20 UTC
### Expected behaviour
Open an Atlas
### Actual behaviour
Error reported
### Steps to reproduce
Open Atlas from rotate and move example from Britzl's Defold examples
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>e6b3e14db1c069651d410877ca5e07596bcc4edc</td></tr>
<tr><td>Build time</td><td>2017-01-11T10:00:14.875260</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=d8694d73f1a44c9fa027934f194e2ed4'>d8694d73f1a44c9fa027934f194e2ed4</a></td></tr>
<table>

**Comment by ragnard-king** [comment] 2017-01-20 09:46
Thanks for the report @CoCopia!

I tried to reproduce this but I did not get an error when opening that atlas from a new checkout of @britzls repo . Are you able to consistently reproduce the problem? Did you open any other files first, or make any changes?

**Comment by ragnard-king** [comment] 2017-01-20 09:50
Ignore previous comment, was able to reproduce. Happens when, for example, images files are missing but referenced in atlas.

**Comment by ragnard-king** [comment] 2017-01-20 11:50
Duplicate of https://github.com/defold/editor2-issues/issues/387

**Comment by ragnard-king** [comment] 2017-01-23 14:56
Fix merged, coming in update shortly.

**Closed by ragnard-king** 2017-01-23 14:56 UTC
Labels: blocker
