### ISSUE TITLE
Starting the project with a broken path to an atlas requires a restart after fixing the path

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#698] opened 2017-04-18 10:55 UTC
### Expected behaviour
When I start a project with an invalid path to a resource and I correct the path it should be possible to build the project.

### Actual behaviour
It's not possible to build the project.

### Steps to reproduce
Create a project with an atlas, a collection, a game object and a sprite
Assign the atlas and an animation/image in the atlas to the sprite
Close the editor
Modify the collection file so that sprite has an invalid path to the atlas
Open the project
Update the path to a valid atlas/image
Notice that the scene editor shows the correct image
Try to build. Notice that there is a build error still referencing the invalid path.
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.102</td></tr>
<tr><td>Defold sha</td><td>72fe1976c208afae6f741f7d35420b525c38bfc7</td></tr>
<tr><td>Build time</td><td>2017-04-18T12:09:42.218860</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment] 2017-04-25 15:25
I can't repro this, can you? Do you have a sample broken project I can have a look at?

**Comment by erikangelin-king** [comment] 2017-05-18 09:32
Closing as cannot reproduce.

**Closed by erikangelin-king** 2017-05-18 09:32 UTC
Labels: more-info, serious
