### ISSUE TITLE
Editor 2.0 Crashes when I click in "Scene Editor"

### ISSUE THREAD

**Issue by sandcoder** [defold/editor2-issues#366] opened 2016-12-27 11:10 UTC
This problem has been bugging me for a while now.

When I am editing a GUI scene (this happens for collection views as well but mostly GUI scenes),
and I click in the scene area, or on the "rulers" that are located on the edges of the window, <em><b>sometimes</b></em> the editor crashes, and I get one of those message saying:
"Defold 2.0 crashed unexpectedly"
"Ignore" "Report" "..."

I haven't really found a consistent pattern for when this happens.
It <em>seems</em> that when I am pressing two buttons simultaniously, for example right and left click, or Ctrl + Alt + Click and then switch quickly it crashes more often, but this is just a guess.
<hr/>
Defold version: 1.2.95
Defold sha: 2fd8732d146f5a252125ce1b210e3793f50e169c
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by matgis-king** [comment] 2017-01-05 10:41
Duplicate of #370, which has more info and a test scene that can be used to reproduce the error. Closing as duplicate.

**Closed by matgis-king** 2017-01-05 10:41 UTC
Labels: blocker, more-info
