### ISSUE TITLE
Rename Bug

### ISSUE THREAD

**Issue by ThaPro** [defold/editor2-issues#804] opened 2017-05-11 15:54 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>7b2ef0aa2f657205c680ddded145b245e11a8ed7</td></tr>
<tr><td>Build time</td><td>2017-05-10T13:30:34.611101</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=ab184a26e19243d78cafb1e2b4964ef4'>ab184a26e19243d78cafb1e2b4964ef4</a></td></tr>
<table>

**Comment by subsoap** [comment] 2017-05-11 18:36
Dupe of https://github.com/defold/editor2-issues/issues/781 ?

**Comment by subsoap** [comment] 2017-05-11 18:36
Dupe of https://github.com/defold/editor2-issues/issues/781 ?

**Comment by erikangelin-king** [comment] 2017-05-18 09:07
Fixed!

**Closed by erikangelin-king** 2017-05-18 09:07 UTC
Labels: blocker
