### ISSUE TITLE
ı cant open defold 2 engine please help me

### ISSUE THREAD

**Issue by Bahattin36** [defold/editor2-issues#1084] opened 2017-07-27 16:46 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.110</td></tr>
<tr><td>Defold sha</td><td>1c336344a6e1542b965b96a0613d3cce56626e2c</td></tr>
<tr><td>Build time</td><td>2017-07-27T17:02:08.098498</td></tr>
<tr><td>OS name</td><td>Windows 8.1</td></tr>
<tr><td>OS version</td><td>6.3</td></tr>
<tr><td>OS arch</td><td>x86</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=a75a6c6ffebd431098177523538c6d60'>a75a6c6ffebd431098177523538c6d60</a></td></tr>
<table>

**Comment by erikangelin-king** [comment] 2017-07-27 17:38
Hmm. Could you please try restarting the editor, and if that doesn't work download a new version from the dashboard?

**Comment by Bahattin36** [comment] 2017-07-27 17:51
Yes ı do it

27 Tem 2017 20:38 tarihinde "erikangelin-king" <notifications@github.com>
yazdı:

**Comment by Bahattin36** [comment] 2017-07-27 17:54
But not open

27 Tem 2017 20:51 tarihinde "Bahattin Aslan" <bahokral3634@gmail.com> yazdı:

**Comment by erikangelin-king** [comment] 2017-07-27 18:09
I'm having trouble reproing this. Does it happen when you try Open Project>From Dashboard from the start screen, or when you choose File>Synchronize or as part of building/signing?

**Comment by Bahattin36** [comment] 2017-07-27 18:13
I'm having trouble logging in to the account

27 Tem 2017 21:09 tarihinde "erikangelin-king" <notifications@github.com>
yazdı:

**Comment by erikangelin-king** [comment] 2017-07-27 18:18
Do you mean the google login screen doesn't work when trying to open a project from the dashboard? Any screenshots of what happens would really help!

**Comment by Bahattin36** [comment] 2017-07-27 18:54
The account gives this error immediately after logging in

27 Tem 2017 21:18 tarihinde "erikangelin-king" <notifications@github.com>
yazdı:

**Comment by erikangelin-king** [comment] 2017-07-27 22:21
Looking at the stacktrace this looks like the same problem that caused #1078. The fix we merged for that issue apparently wasn't sufficient. We'll revisit this when we're back from vacations!

**Comment by Bahattin36** [comment] 2017-07-28 08:01
Okey thanks

28 Tem 2017 01:21 tarihinde "erikangelin-king" <notifications@github.com>
yazdı:

**Comment by matgis-king** [comment] 2017-08-01 09:37
I'm also having trouble reproducing this. In order to get more information, we've tried to catch the error and append additional info to it in case it happens again.

An updated version of the editor should reach you in about an hour or so. If you could try to reproduce the error and report it again, the new error report should hopefully contain a bit more information that would help us track down what went wrong!

**Comment by matgis-king** [comment] 2017-08-07 08:48
This is a duplicate of #1099, which has more info in the sentry report.

**Comment by ragnard-king** [comment] 2017-08-11 09:23
This issue should be resolved in latest update.

**Closed by ragnard-king** 2017-08-11 09:23 UTC
Labels: blocker, duplicate
