### ISSUE TITLE
When deleting a .lua file from a project [DEFEDIT-1341]

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1787] opened 2018-04-04 00:14 UTC
java.lang.ClassCastException: internal.graph.error_values.ErrorValue cannot be cast to editor.code.data.LayoutInfo

<hr/>

<table>
<tr><td>Build time</td><td>2018-03-29T10:04:12.285850</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7b3ad804702670db33809955240a5de3671111b8</td></tr>
<tr><td>Defold engine sha</td><td>e3f2a48e6495946eb8aede3c843471bb037976aa</td></tr>
<tr><td>Defold version</td><td>1.2.124</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"3bf4100b68664183b41ab79205a985c5"'>3bf4100b68664183b41ab79205a985c5</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 750/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 390.65</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment] 2018-04-04 07:54
Duplicate of #1775. The fix was merged with defold/defold#2196 on 2018-04-03.

**Closed by matgis-king** 2018-04-04 07:54 UTC
Labels: duplicate, serious
