### ISSUE TITLE
yy

### ISSUE THREAD

**Issue by Egoranator** [defold/editor2-issues#2775] opened 2019-10-05 13:46 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-01-21T13:07:31.819071</td></tr>
<tr><td>Defold channel</td><td>stable</td></tr>
<tr><td>Defold editor sha</td><td>9f376d88408bad9088a4187d4f874ae4767a0185</td></tr>
<tr><td>Defold engine sha</td><td>9f376d88408bad9088a4187d4f874ae4767a0185</td></tr>
<tr><td>Defold version</td><td>1.2.145</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"5c47c28806314a6a991b61bbdf5667b7"'>5c47c28806314a6a991b61bbdf5667b7</a></td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by matgis-king** [comment] 2019-10-08 08:16
Duplicate of #2692 with no additional info.

**Closed by matgis-king** 2019-10-08 08:16 UTC
Labels: duplicate, jdk, serious
